import React, { createContext, useContext, useState } from "react";


// ── Language Context ────────────────────────────────────────────
const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState("ta"); // "ta" = Tamil, "en" = English

  const toggleLanguage = () => {
    setLanguage((prev) => (prev === "ta" ? "en" : "ta"));
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, toggleLanguage }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => useContext(LanguageContext);

// ── Quiz Data ────────────────────────────────────────────────────
export const COMPLETED_CATEGORIES_KEY = "hdrss_quiz_completed_categories";

export const QUIZ_CATEGORIES = [
  // ── CATEGORY 1 ──
  {
    id: "dharma",
    title: { ta: "இந்து தர்ம அடிப்படைகள்", en: "Hindu Dharma Basics" },
    description: { ta: "அடிப்படைக் கருத்துகள் மற்றும் மதிப்புகள்", en: "Core ideas, values and symbols" },
    icon: "self-improvement",
    color: "#E65100",
    questions: [
      { question: { ta: "'தர்மம்' என்ற சொல் பொதுவாக எதைக் குறிக்கிறது?", en: "What does the word 'Dharma' generally refer to?" }, options: { ta: ["சரியான நடத்தை மற்றும் கடமை", "ஒரு இசைக்கருவி", "ஒரு கோபுரம்", "ஒரு வகை உணவு"], en: ["Righteous conduct and duty", "A musical instrument", "A tower", "A type of food"] }, answer: 0 },
      { question: { ta: "எந்தக் கொள்கை அகிம்சையைக் குறிக்கிறது?", en: "Which principle refers to non-violence?" }, options: { ta: ["அஹிம்சை", "அர்த்தம்", "மோக்ஷம்", "யாகம்"], en: ["Ahimsa", "Artha", "Moksha", "Yagna"] }, answer: 0 },
      { question: { ta: "கர்மா என்றால் என்ன?", en: "What is Karma?" }, options: { ta: ["செயல் மற்றும் விளைவின் விதி", "ஒரு புனித நதி", "ஒரு திருவிழா", "ஒரு கட்டிட பாணி"], en: ["The law of action and consequence", "A sacred river", "A festival", "An architectural style"] }, answer: 0 },
      { question: { ta: "வாழ்க்கையின் எந்த இலக்கு ஆன்மீக விடுதலையைக் குறிக்கிறது?", en: "Which life goal represents spiritual liberation?" }, options: { ta: ["மோக்ஷம்", "அர்த்தம்", "காமம்", "தானம்"], en: ["Moksha", "Artha", "Kama", "Dana"] }, answer: 0 },
      { question: { ta: "பாரம்பரிய புருஷார்த்தங்கள் (வாழ்க்கை இலக்குகள்) எத்தனை உள்ளன?", en: "How many traditional Purusharthas (life goals) are there?" }, options: { ta: ["இரண்டு", "மூன்று", "நான்கு", "ஏழு"], en: ["Two", "Three", "Four", "Seven"] }, answer: 2 },
      { question: { ta: "எந்த ஒலி புனிதமான ஆதி எழுத்தாகக் கருதப்படுகிறது?", en: "Which sound is considered the sacred primordial syllable?" }, options: { ta: ["ஓம்", "ராம்", "ஸ்ரீ", "ஹும்"], en: ["Om", "Raam", "Shri", "Hum"] }, answer: 0 },
      { question: { ta: "'நமஸ்தே' எதை மரியாதையுடன் ஏற்றுக்கொள்கிறது?", en: "What does 'Namaste' respectfully acknowledge?" }, options: { ta: ["மற்றவரில் உள்ள தெய்வீகத்தை", "ஒரு முறையான பட்டத்தை மட்டும்", "ஒரு இடத்தின் பெயரை", "ஒரு உணவை"], en: ["The divine within the other person", "A formal title only", "The name of a place", "A food item"] }, answer: 0 },
      { question: { ta: "எந்தப் பயிற்சி தோரணைகள், சுவாசம் மற்றும் தியானத்தைப் பயன்படுத்தி ஒழுங்கான ஒன்றிணைப்பை அடைகிறது?", en: "Which practice uses postures, breath and meditation to achieve union?" }, options: { ta: ["யோகா", "ரங்கோலி", "ஆரத்தி", "பிரதக்ஷிணம்"], en: ["Yoga", "Rangoli", "Aarti", "Pradakshina"] }, answer: 0 },
      { question: { ta: "சேவா என்றால் என்ன?", en: "What is Seva?" }, options: { ta: ["தன்னலமற்ற சேவை", "ஒரு அரச விழா", "ஒரு வகை நூல்", "ஒரு யாத்திரை வரி"], en: ["Selfless service", "A royal ceremony", "A type of text", "A pilgrimage tax"] }, answer: 0 },
      { question: { ta: "சத்சங்கம் என்றால் என்ன?", en: "What is Satsangam?" }, options: { ta: ["உண்மையின் துணை அல்லது ஆன்மீக கூட்டமைப்பு", "ஒரு அறுவடை கருவி", "ஒரு கோவில் நுழைவாயில்", "ஒரு திருமண ஆடை"], en: ["Company of truth or a spiritual gathering", "A harvest tool", "A temple entrance", "A wedding garment"] }, answer: 0 },
      { question: { ta: "எந்த நற்பண்பு உண்மைத்தன்மையைக் குறிக்கிறது?", en: "Which virtue represents truthfulness?" }, options: { ta: ["சத்யம்", "பக்தி", "மாயா", "லீலா"], en: ["Satyam", "Bhakti", "Maya", "Leela"] }, answer: 0 },
      { question: { ta: "சம்சாரம் என்றால் என்ன?", en: "What is Samsara?" }, options: { ta: ["பிறப்பு மற்றும் மறுபிறப்பின் சுழற்சி", "ஒரு கோவில் விளக்கு", "ஒரு புனித நூல் மட்டும்", "ஒரு நடன பள்ளி"], en: ["The cycle of birth and rebirth", "A temple lamp", "A sacred text only", "A dance school"] }, answer: 0 },
      { question: { ta: "எந்த பாதை இறைவன் மீதான பக்தியை வலியுறுத்துகிறது?", en: "Which path emphasizes devotion to God?" }, options: { ta: ["பக்தி யோகா", "கர்ம யோகா", "ஞான யோகா", "ராஜ யோகா"], en: ["Bhakti Yoga", "Karma Yoga", "Gyana Yoga", "Raja Yoga"] }, answer: 0 },
      { question: { ta: "எந்த பாதை தன்னலமற்ற செயலை வலியுறுத்துகிறது?", en: "Which path emphasizes selfless action?" }, options: { ta: ["கர்ம யோகா", "பக்தி யோகா", "ஞான யோகா", "நாத யோகா"], en: ["Karma Yoga", "Bhakti Yoga", "Gyana Yoga", "Nada Yoga"] }, answer: 0 },
      { question: { ta: "வணக்கத்தின் போது அறிவு இருளை வெல்வதன் அடையாளமாக பொதுவாக எது ஏற்றப்படுகிறது?", en: "What is commonly lit during worship to symbolize knowledge overcoming darkness?" }, options: { ta: ["ஒரு தீபம்", "ஒரு சங்கு மட்டும்", "ஒரு மணி கயிறு", "ஒரு கொடிக்கம்பம்"], en: ["A lamp (Deepam)", "A conch shell only", "A bell rope", "A flagpole"] }, answer: 0 },
    ],
  },
  // ── CATEGORY 2 ──
  {
    id: "scriptures",
    title: { ta: "புனித நூல்கள்", en: "Sacred Texts" },
    description: { ta: "வேதங்கள், இதிகாசங்கள் மற்றும் ஆன்மீக போதனைகள்", en: "Vedas, epics and spiritual teachings" },
    icon: "menu-book",
    color: "#8E3B18",
    questions: [
      { question: { ta: "வேதங்கள் எத்தனை உள்ளன?", en: "How many Vedas are there?" }, options: { ta: ["இரண்டு", "மூன்று", "நான்கு", "ஆறு"], en: ["Two", "Three", "Four", "Six"] }, answer: 2 },
      { question: { ta: "எது பழமையான வேதம்?", en: "Which is the oldest Veda?" }, options: { ta: ["ரிக் வேதம்", "சாம வேதம்", "யஜுர் வேதம்", "அதர்வண வேதம்"], en: ["Rig Veda", "Sama Veda", "Yajur Veda", "Atharva Veda"] }, answer: 0 },
      { question: { ta: "பகவத் கீதை எந்த இதிகாசத்தின் பகுதியாகும்?", en: "The Bhagavad Gita is part of which epic?" }, options: { ta: ["மகாபாரதம்", "ராமாயணம்", "ரிக் வேதம்", "யோக சூத்திரங்கள்"], en: ["Mahabharata", "Ramayana", "Rig Veda", "Yoga Sutras"] }, answer: 0 },
      { question: { ta: "பகவத் கீதையில் அர்ஜுனனுக்குப் போதிப்பவர் யார்?", en: "Who teaches Arjuna in the Bhagavad Gita?" }, options: { ta: ["கிருஷ்ணர்", "ராமர்", "அனுமன்", "பீஷ்மர்"], en: ["Krishna", "Rama", "Hanuman", "Bhishma"] }, answer: 0 },
      { question: { ta: "ராமாயணத்தை இயற்றியவராக பாரம்பரியமாகக் கருதப்படுபவர் யார்?", en: "Who is traditionally regarded as the author of the Ramayana?" }, options: { ta: ["வால்மீகி", "வியாசர்", "காளிதாசர்", "பதஞ்சலி"], en: ["Valmiki", "Vyasa", "Kalidasa", "Patanjali"] }, answer: 0 },
      { question: { ta: "மகாபாரதத்தைத் தொகுத்தவராக பாரம்பரியமாகக் கருதப்படுபவர் யார்?", en: "Who is traditionally regarded as the compiler of the Mahabharata?" }, options: { ta: ["வியாசர்", "வால்மீகி", "துளசிதாஸ்", "பாணினி"], en: ["Vyasa", "Valmiki", "Tulsidas", "Panini"] }, answer: 0 },
      { question: { ta: "எந்த நூல்கள் வேதங்களின் தத்துவ போதனைகளை ஆராய்கின்றன?", en: "Which texts explore the philosophical teachings of the Vedas?" }, options: { ta: ["உபநிடதங்கள்", "புராணங்கள் மட்டும்", "ஆகமங்கள் மட்டும்", "இதிகாசங்கள் மட்டும்"], en: ["Upanishads", "Puranas only", "Agamas only", "Itihasas only"] }, answer: 0 },
      { question: { ta: "எந்த வேதம் குறிப்பாக இராகங்கள் மற்றும் மந்திரங்களுடன் தொடர்புடையது?", en: "Which Veda is specifically associated with melodies and chants?" }, options: { ta: ["சாம வேதம்", "ரிக் வேதம்", "அதர்வண வேதம்", "யஜுர் வேதம்"], en: ["Sama Veda", "Rig Veda", "Atharva Veda", "Yajur Veda"] }, answer: 0 },
      { question: { ta: "எந்த வேதத்தில் யாக சடங்குகளில் பயன்படும் பல மந்திரங்கள் உள்ளன?", en: "Which Veda contains many mantras used in sacrificial rituals?" }, options: { ta: ["யஜுர் வேதம்", "சாம வேதம்", "ரிக் வேதம்", "நாட்டிய சாஸ்திரம்"], en: ["Yajur Veda", "Sama Veda", "Rig Veda", "Natya Shastra"] }, answer: 0 },
      { question: { ta: "ராமாயணமும் மகாபாரதமும் ஒன்றாக என்ன அழைக்கப்படுகின்றன?", en: "What are the Ramayana and Mahabharata together called?" }, options: { ta: ["இதிகாசம்", "வேதாங்கம்", "தர்சனம்", "ஸ்தோத்திரம்"], en: ["Itihasa", "Vedanga", "Darshana", "Stotra"] }, answer: 0 },
      { question: { ta: "நசிகேதனுக்கும் யமனுக்கும் இடையேயான உரையாடல் எந்த நூலில் உள்ளது?", en: "The dialogue between Nachiketa and Yama appears in which text?" }, options: { ta: ["கட உபநிடதம்", "பாகவத புராணம்", "ராமாயணம்", "மனுஸ்மிருதி"], en: ["Katha Upanishad", "Bhagavata Purana", "Ramayana", "Manusmriti"] }, answer: 0 },
      { question: { ta: "யோக சூத்திரங்கள் யாருடன் தொடர்புடையவை?", en: "The Yoga Sutras are associated with whom?" }, options: { ta: ["பதஞ்சலி", "வால்மீகி", "வியாசர்", "திருவள்ளுவர்"], en: ["Patanjali", "Valmiki", "Vyasa", "Thiruvalluvar"] }, answer: 0 },
      { question: { ta: "எந்த தமிழ் இலக்கியம் அறம், பொருள், இன்பம் ஆகியவற்றை சுருக்கமான குறள்களில் கற்பிக்கிறது?", en: "Which Tamil work teaches virtue, wealth and love through short couplets?" }, options: { ta: ["திருக்குறள்", "சிலப்பதிகாரம்", "மணிமேகலை", "தேவாரம்"], en: ["Thirukkural", "Silappathikaram", "Manimekalai", "Thevaram"] }, answer: 0 },
      { question: { ta: "தேவார பாடல்கள் முதன்மையாக எந்தக் கடவுளுக்கு அர்ப்பணிக்கப்பட்டவை?", en: "The Thevaram hymns are primarily dedicated to which deity?" }, options: { ta: ["சிவன்", "விஷ்ணு", "சூரியன்", "பிரம்மா"], en: ["Shiva", "Vishnu", "Surya", "Brahma"] }, answer: 0 },
      { question: { ta: "திவ்விய பிரபந்த பாடல்கள் முதன்மையாக எந்தக் கடவுளுக்கு அர்ப்பணிக்கப்பட்டவை?", en: "The Divya Prabandham hymns are primarily dedicated to which deity?" }, options: { ta: ["விஷ்ணு", "சிவன்", "அக்னி", "இந்திரன்"], en: ["Vishnu", "Shiva", "Agni", "Indra"] }, answer: 0 },
    ],
  },
  // ── CATEGORY 3 ──
  {
    id: "deities",
    title: { ta: "தெய்வங்களும் சின்னங்களும்", en: "Deities & Symbols" },
    description: { ta: "வடிவங்கள், பண்புகள் மற்றும் புனித சின்னங்கள்", en: "Forms, attributes and sacred symbols" },
    icon: "flare",
    color: "#B23A48",
    questions: [
      { question: { ta: "தடைகளை நீக்குபவராக பரவலாக அறியப்படும் கடவுள் யார்?", en: "Which deity is widely known as the remover of obstacles?" }, options: { ta: ["விநாயகர்", "சூரியன்", "அக்னி", "இந்திரன்"], en: ["Vinayagar (Ganesha)", "Surya", "Agni", "Indra"] }, answer: 0 },
      { question: { ta: "திரிசூலம் மற்றும் உடுக்கையுடன் எந்தக் கடவுள் சித்தரிக்கப்படுகிறார்?", en: "Which deity is depicted with a trident and a small drum?" }, options: { ta: ["சிவன்", "விஷ்ணு", "பிரம்மா", "விநாயகர்"], en: ["Shiva", "Vishnu", "Brahma", "Vinayagar"] }, answer: 0 },
      { question: { ta: "கருடன் எந்தக் கடவுளின் வாகனம்?", en: "Garuda is the vehicle of which deity?" }, options: { ta: ["விஷ்ணு", "சிவன்", "முருகன்", "விநாயகர்"], en: ["Vishnu", "Shiva", "Murugan", "Vinayagar"] }, answer: 0 },
      { question: { ta: "கல்வி, இசை மற்றும் வீணையுடன் தொடர்புடைய தேவி யார்?", en: "Which goddess is associated with knowledge, music and the veena?" }, options: { ta: ["சரஸ்வதி", "லட்சுமி", "பார்வதி", "கங்கை"], en: ["Saraswati", "Lakshmi", "Parvati", "Ganga"] }, answer: 0 },
      { question: { ta: "செல்வம் மற்றும் வளத்துடன் தொடர்புடைய தேவி யார்?", en: "Which goddess is associated with wealth and prosperity?" }, options: { ta: ["லட்சுமி", "சரஸ்வதி", "துர்கை", "சீதை"], en: ["Lakshmi", "Saraswati", "Durga", "Sita"] }, answer: 0 },
      { question: { ta: "ராமாயணத்தில் ராமனின் பக்தியுள்ள தோழர் யார்?", en: "Who is Rama's devoted companion in the Ramayana?" }, options: { ta: ["அனுமன்", "அர்ஜுனன்", "பீமன்", "நாரதர்"], en: ["Hanuman", "Arjuna", "Bhima", "Narada"] }, answer: 0 },
      { question: { ta: "எந்தக் கடவுள் ஸ்கந்தர் மற்றும் கார்த்திகேயன் என்றும் அழைக்கப்படுகிறார்?", en: "Which deity is also known as Skanda and Karthikeyan?" }, options: { ta: ["முருகன்", "விநாயகர்", "கிருஷ்ணர்", "ஐயப்பன்"], en: ["Murugan", "Vinayagar", "Krishna", "Ayyappan"] }, answer: 0 },
      { question: { ta: "முருகனின் வேலின் பெயர் என்ன?", en: "What is the name of Murugan's spear?" }, options: { ta: ["வேல்", "வஜ்ரம்", "சக்கரம்", "கதை"], en: ["Vel", "Vajra", "Chakra", "Gada"] }, answer: 0 },
      { question: { ta: "சிவனின் சடையிலிருந்து இறங்கும் தேவியாக உருவகப்படுத்தப்படும் புனித நதி எது?", en: "Which sacred river is depicted as a goddess descending from Shiva's hair?" }, options: { ta: ["கங்கை", "யமுனை", "கோதாவரி", "காவிரி"], en: ["Ganga", "Yamuna", "Godavari", "Kaveri"] }, answer: 0 },
      { question: { ta: "கிருஷ்ணருடன் நெருக்கமாக தொடர்புடைய இசைக்கருவி எது?", en: "Which musical instrument is closely associated with Krishna?" }, options: { ta: ["புல்லாங்குழல்", "வீணை", "உடுக்கை", "மிருதங்கம்"], en: ["Flute", "Veena", "Damaru", "Mridangam"] }, answer: 0 },
      { question: { ta: "விஷ்ணுவின் சக்கரத்தின் பெயர் என்ன?", en: "What is the name of Vishnu's discus?" }, options: { ta: ["சுதர்சன சக்கரம்", "திரிசூலம்", "பினாகம்", "வஜ்ரம்"], en: ["Sudarshana Chakra", "Trishula", "Pinaka", "Vajra"] }, answer: 0 },
      { question: { ta: "சிவனின் வாகனம் எந்த விலங்கு?", en: "Which animal is Shiva's vehicle?" }, options: { ta: ["நந்தி (ரிஷபம்)", "கருடன்", "எலி", "மயில்"], en: ["Nandi (Bull)", "Garuda", "Mouse", "Peacock"] }, answer: 0 },
      { question: { ta: "விநாயகரின் பாரம்பரிய வாகனம் எந்த விலங்கு?", en: "Which animal is Vinayagar's traditional vehicle?" }, options: { ta: ["எலி", "சிங்கம்", "யானை", "குதிரை"], en: ["Mouse", "Lion", "Elephant", "Horse"] }, answer: 0 },
      { question: { ta: "மயில் பாரம்பரியமாக எந்தக் கடவுளின் வாகனம்?", en: "The peacock is traditionally the vehicle of which deity?" }, options: { ta: ["முருகன்", "விஷ்ணு", "சூரியன்", "பிரம்மா"], en: ["Murugan", "Vishnu", "Surya", "Brahma"] }, answer: 0 },
      { question: { ta: "சிவனை அண்டத்தின் நடனமாடுபவராகக் காட்டும் வடிவம் எது?", en: "Which form depicts Shiva as the cosmic dancer?" }, options: { ta: ["நடராஜர்", "தக்ஷிணாமூர்த்தி", "அர்த்தநாரீஸ்வரர்", "லிங்கோத்பவர்"], en: ["Nataraja", "Dakshinamurthy", "Ardhanarishvara", "Lingodbhava"] }, answer: 0 },
    ],
  },
  // ── CATEGORY 4 ──
  {
    id: "festivals",
    title: { ta: "திருவிழாக்களும் வழிபாடும்", en: "Festivals & Worship" },
    description: { ta: "கொண்டாட்டங்கள், சடங்குகள் மற்றும் பழக்கவழக்கங்கள்", en: "Celebrations, rituals and practices" },
    icon: "celebration",
    color: "#D97706",
    questions: [
      { question: { ta: "ஒளிகளின் திருவிழா என பரவலாக அறியப்படும் பண்டிகை எது?", en: "Which festival is widely known as the Festival of Lights?" }, options: { ta: ["தீபாவளி", "ஹோலி", "நவராத்திரி", "ஓணம்"], en: ["Deepavali", "Holi", "Navaratri", "Onam"] }, answer: 0 },
      { question: { ta: "கிருஷ்ணரின் பிறப்பை கொண்டாடும் பண்டிகை எது?", en: "Which festival celebrates the birth of Krishna?" }, options: { ta: ["கிருஷ்ண ஜென்மாஷ்டமி", "ராம நவமி", "மகா சிவராத்திரி", "விஜயதசமி"], en: ["Krishna Janmashtami", "Rama Navami", "Maha Shivaratri", "Vijayadashami"] }, answer: 0 },
      { question: { ta: "ராமரின் பிறப்பை கொண்டாடும் பண்டிகை எது?", en: "Which festival celebrates the birth of Rama?" }, options: { ta: ["ராம நவமி", "ஜென்மாஷ்டமி", "விநாயகர் சதுர்த்தி", "கார்த்திகை தீபம்"], en: ["Rama Navami", "Janmashtami", "Vinayagar Chaturthi", "Karthigai Deepam"] }, answer: 0 },
      { question: { ta: "எந்த இரவு குறிப்பாக சிவனுக்கு அர்ப்பணிக்கப்பட்டது?", en: "Which night is specifically dedicated to Shiva?" }, options: { ta: ["மகா சிவராத்திரி", "வைகுண்ட ஏகாதசி", "அக்ஷய திரிதியை", "குரு பூர்ணிமா"], en: ["Maha Shivaratri", "Vaikunta Ekadasi", "Akshaya Tritiya", "Guru Purnima"] }, answer: 0 },
      { question: { ta: "நவராத்திரி எத்தனை இரவுகள் கொண்டாடப்படுகிறது?", en: "For how many nights is Navaratri celebrated?" }, options: { ta: ["ஐந்து", "ஏழு", "ஒன்பது", "பன்னிரண்டு"], en: ["Five", "Seven", "Nine", "Twelve"] }, answer: 2 },
      { question: { ta: "சூரியனையும் புதிய அறுவடையையும் கொண்டாடும் தமிழ் அறுவடைத் திருவிழா எது?", en: "Which Tamil harvest festival celebrates the sun and the new harvest?" }, options: { ta: ["பொங்கல்", "ஓணம்", "ஹோலி", "ரக்ஷா பந்தன்"], en: ["Pongal", "Onam", "Holi", "Raksha Bandhan"] }, answer: 0 },
      { question: { ta: "கார்த்திகை தீபத்தின்போது ஏற்றப்படும் மகா தீபம் எந்த இடத்தில் சிறப்பாக அறியப்படுகிறது?", en: "The great flame lit during Karthigai Deepam is especially known at which place?" }, options: { ta: ["திருவண்ணாமலை", "மதுரை", "ராமேஸ்வரம்", "காஞ்சிபுரம்"], en: ["Thiruvannamalai", "Madurai", "Rameswaram", "Kanchipuram"] }, answer: 0 },
      { question: { ta: "ஆரத்தி என்றால் என்ன?", en: "What is Aarti?" }, options: { ta: ["கடவுளுக்கு முன் விளக்கேற்றி காணிக்கையாக்குதல்", "ஒரு கோவில் கோபுரம்", "ஒரு புனித நூல்", "ஒரு விரத நாள்"], en: ["Offering a lit lamp before God", "A temple tower", "A sacred text", "A fasting day"] }, answer: 0 },
      { question: { ta: "பிரதக்ஷிணம் என்றால் என்ன?", en: "What is Pradakshina?" }, options: { ta: ["ஒரு புனிதப் பொருளை வலம் வருதல்", "சமையல் நெருப்பை மூட்டுதல்", "ஜாதகம் படித்தல்", "கோவில் வரைபடம் வரைதல்"], en: ["Circumambulating a sacred object", "Lighting a cooking fire", "Reading a horoscope", "Drawing a temple map"] }, answer: 0 },
      { question: { ta: "பிரசாதம் என்றால் என்ன?", en: "What is Prasadam?" }, options: { ta: ["பக்தர்களுக்கு பகிரப்படும் ஆசீர்வதிக்கப்பட்ட காணிக்கை", "ஒரு கோவில் மேளம்", "ஒரு பூசாரி ஆடை", "ஒரு யாத்திரை பாதை"], en: ["Blessed offering shared with devotees", "A temple drum", "A priest's garment", "A pilgrimage route"] }, answer: 0 },
      { question: { ta: "வண்ணங்களுடன் வசந்த காலத்தை வரவேற்கும் பண்டிகை எது?", en: "Which festival welcomes spring with colors?" }, options: { ta: ["ஹோலி", "தீபாவளி", "பொங்கல்", "மகா சிவராத்திரி"], en: ["Holi", "Deepavali", "Pongal", "Maha Shivaratri"] }, answer: 0 },
      { question: { ta: "விநாயகர் சதுர்த்தி எந்தக் கடவுளை கொண்டாடுகிறது?", en: "Vinayagar Chaturthi celebrates which deity?" }, options: { ta: ["விநாயகர்", "கிருஷ்ணர்", "ராமர்", "சூரியன்"], en: ["Vinayagar", "Krishna", "Rama", "Surya"] }, answer: 0 },
      { question: { ta: "விஜயதசமி எந்த பண்டிகை காலத்தின் முடிவைக் குறிக்கிறது?", en: "Vijayadashami marks the end of which festival period?" }, options: { ta: ["நவராத்திரி", "பொங்கல்", "ஹோலி", "ஓணம்"], en: ["Navaratri", "Pongal", "Holi", "Onam"] }, answer: 0 },
      { question: { ta: "விரதம் என்றால் என்ன?", en: "What is Vratam?" }, options: { ta: ["ஒரு மத விரதம் அல்லது நோன்பு", "ஒரு கோவில் வாகனம்", "ஒரு இசை ஸ்கேல்", "ஒரு நூல் அத்தியாயம்"], en: ["A religious vow or fast", "A temple vehicle", "A musical scale", "A book chapter"] }, answer: 0 },
      { question: { ta: "பல வைணவ வீடுகளில் குறிப்பாக புனிதமாகக் கருதப்படும் செடி எது?", en: "Which plant is considered especially sacred in many Vaishnavite homes?" }, options: { ta: ["துளசி", "ரோஜா", "மல்லிகை", "ஆலமரம் மட்டும்"], en: ["Tulsi", "Rose", "Jasmine", "Banyan tree only"] }, answer: 0 },
    ],
  },
  // ── CATEGORY 5 ──
  {
    id: "temples",
    title: { ta: "கோவில்களும் யாத்திரையும்", en: "Temples & Pilgrimage" },
    description: { ta: "புனித இடங்களும் கோவில் பாரம்பரியமும்", en: "Sacred places and temple heritage" },
    icon: "account-balance",
    color: "#7C3E12",
    questions: [
      { question: { ta: "மீனாக்ஷி அம்மன் கோவில் தமிழ்நாட்டின் எந்த நகரத்தில் உள்ளது?", en: "In which Tamil Nadu city is the Meenakshi Amman Temple located?" }, options: { ta: ["மதுரை", "சென்னை", "சேலம்", "தஞ்சாவூர்"], en: ["Madurai", "Chennai", "Salem", "Thanjavur"] }, answer: 0 },
      { question: { ta: "ராமநாதசுவாமி கோவில் எந்த யாத்திரை நகரில் அமைந்துள்ளது?", en: "In which pilgrimage town is the Ramanathaswamy Temple located?" }, options: { ta: ["ராமேஸ்வரம்", "காஞ்சிபுரம்", "சிதம்பரம்", "பழனி"], en: ["Rameswaram", "Kanchipuram", "Chidambaram", "Palani"] }, answer: 0 },
      { question: { ta: "முதலாம் ராஜராஜ சோழன் கட்டிய பெருவுடையார் கோவில் (பிரகதீஸ்வரர் கோவில்) எந்த நகரில் உள்ளது?", en: "The Peruvudaiyar Temple (Brihadeeswarar Temple) built by Raja Raja Chola I is in which city?" }, options: { ta: ["தஞ்சாவூர்", "மதுரை", "கோயம்புத்தூர்", "வேலூர்"], en: ["Thanjavur", "Madurai", "Coimbatore", "Vellore"] }, answer: 0 },
      { question: { ta: "நடராஜர் கோவில் எந்த நகரில் அமைந்துள்ளது?", en: "The Nataraja Temple is located in which town?" }, options: { ta: ["சிதம்பரம்", "கும்பகோணம்", "திருநெல்வேலி", "ஸ்ரீரங்கம்"], en: ["Chidambaram", "Kumbakonam", "Tirunelveli", "Srirangam"] }, answer: 0 },
      { question: { ta: "அருணாசலேஸ்வரர் கோவில் எந்த புனித மலை நகரில் அமைந்துள்ளது?", en: "The Arunachaleswarar Temple is located in which sacred hill town?" }, options: { ta: ["திருவண்ணாமலை", "கன்னியாகுமரி", "பழனி", "மயிலாடுதுறை"], en: ["Thiruvannamalai", "Kanyakumari", "Palani", "Mayiladuthurai"] }, answer: 0 },
      { question: { ta: "ஸ்ரீரங்கத்தில் உள்ள ரங்கநாதசுவாமி கோவில் எந்தக் கடவுளுக்கு அர்ப்பணிக்கப்பட்டது?", en: "The Ranganathaswamy Temple in Srirangam is dedicated to which deity?" }, options: { ta: ["விஷ்ணு", "சிவன்", "முருகன்", "விநாயகர்"], en: ["Vishnu", "Shiva", "Murugan", "Vinayagar"] }, answer: 0 },
      { question: { ta: "பழனி எந்தக் கடவுளின் ஆறு படைவீடுகளில் ஒன்று?", en: "Palani is one of the six abodes of which deity?" }, options: { ta: ["முருகன்", "விஷ்ணு", "சிவன்", "ஐயப்பன்"], en: ["Murugan", "Vishnu", "Shiva", "Ayyappan"] }, answer: 0 },
      { question: { ta: "முருகனின் ஆறுபடைவீடுகள் பாரம்பரியமாக எத்தனை எனக் கருதப்படுகின்றன?", en: "How many are the traditional abodes (Arupadaiveedu) of Murugan?" }, options: { ta: ["நான்கு", "ஐந்து", "ஆறு", "எட்டு"], en: ["Four", "Five", "Six", "Eight"] }, answer: 2 },
      { question: { ta: "கடற்கரைக் கோவிலுக்கு பெயர் பெற்ற நகரம் எது?", en: "Which town is famous for its Shore Temple?" }, options: { ta: ["மாமல்லபுரம்", "மதுரை", "சிதம்பரம்", "ஸ்ரீவில்லிபுத்தூர்"], en: ["Mamallapuram", "Madurai", "Chidambaram", "Srivilliputhur"] }, answer: 0 },
      { question: { ta: "சென்னையில் சிவனை கபாலீஸ்வரராக வணங்கும் கோவில் எது?", en: "Which Chennai temple worships Shiva as Kapaleeswarar?" }, options: { ta: ["கபாலீஸ்வரர் கோவில், மயிலாப்பூர்", "பார்த்தசாரதி கோவில்", "வடபழனி கோவில்", "அஷ்டலட்சுமி கோவில்"], en: ["Kapaleeswarar Temple, Mylapore", "Parthasarathy Temple", "Vadapalani Temple", "Ashtalakshmi Temple"] }, answer: 0 },
      { question: { ta: "கோபுரம் தென்னிந்திய கோவிலின் எந்தப் பகுதி?", en: "The Gopuram is which part of a South Indian temple?" }, options: { ta: ["பிரம்மாண்டமான நுழைவாயில் கோபுரம்", "உள் நீர்த் தொட்டி", "கோவில் சமையலறை", "திருவிழா தேர்"], en: ["The grand entrance tower", "The inner water tank", "The temple kitchen", "The festival chariot"] }, answer: 0 },
      { question: { ta: "கர்பகிரகம் என்றால் என்ன?", en: "What is the Garbhagriha?" }, options: { ta: ["உள்ளிருக்கும் கருவறை", "வெளி சந்தை", "கோவில் குளம்", "திருவிழா தெரு"], en: ["The innermost sanctum", "The outer market", "The temple tank", "The festival street"] }, answer: 0 },
      { question: { ta: "கங்கை நதிக்கரையில் உள்ள புனித நகரம் வாரணாசி என்றும் அழைக்கப்படுவது எது?", en: "Which sacred city on the banks of the Ganges is also called Varanasi?" }, options: { ta: ["காசி", "அயோத்தி", "மதுரா", "உஜ்ஜைன்"], en: ["Kasi", "Ayodhya", "Mathura", "Ujjain"] }, answer: 0 },
      { question: { ta: "ஜகந்நாதர் கோவில் எந்த நகரில் அமைந்துள்ளது?", en: "The Jagannath Temple is located in which city?" }, options: { ta: ["பூரி", "துவாரகா", "ஹரித்வார்", "நாசிக்"], en: ["Puri", "Dwaraka", "Haridwar", "Nashik"] }, answer: 0 },
      { question: { ta: "திருமலை மலையில் அமைந்துள்ள கோவில் எது?", en: "Which temple is located on the Tirumala hills?" }, options: { ta: ["ஸ்ரீ வேங்கடேஸ்வரர் கோவில்", "சோம்நாத் கோவில்", "கேதார்நாத் கோவில்", "லிங்கராஜா கோவில்"], en: ["Sri Venkateswara Temple", "Somnath Temple", "Kedarnath Temple", "Lingaraja Temple"] }, answer: 0 },
    ],
  },
  // ── CATEGORY 6 ──
  {
    id: "philosophy",
    title: { ta: "இந்து தத்துவம்", en: "Hindu Philosophy" },
    description: { ta: "ஆழ்ந்த தத்துவக் கருத்துகள் மற்றும் பள்ளிகள்", en: "Deep philosophical concepts and schools" },
    icon: "psychology",
    color: "#1A6B8A",
    questions: [
      { question: { ta: "அத்வைத வேதாந்தத்தின் முக்கிய போதகர் யார்?", en: "Who is the main proponent of Advaita Vedanta?" }, options: { ta: ["ஆதி சங்கரர்", "ராமானுஜர்", "மத்வர்", "கௌடபாதர்"], en: ["Adi Shankara", "Ramanuja", "Madhva", "Gaudapada"] }, answer: 0 },
      { question: { ta: "விசிஷ்டாத்வைத வேதாந்தத்தின் முக்கிய போதகர் யார்?", en: "Who is the main proponent of Vishishtadvaita Vedanta?" }, options: { ta: ["ராமானுஜர்", "ஆதி சங்கரர்", "மத்வர்", "நிம்பர்கர்"], en: ["Ramanuja", "Adi Shankara", "Madhva", "Nimbarka"] }, answer: 0 },
      { question: { ta: "துவைத வேதாந்தத்தின் முக்கிய போதகர் யார்?", en: "Who is the main proponent of Dvaita Vedanta?" }, options: { ta: ["மத்வர்", "ராமானுஜர்", "ஆதி சங்கரர்", "பதஞ்சலி"], en: ["Madhva", "Ramanuja", "Adi Shankara", "Patanjali"] }, answer: 0 },
      { question: { ta: "அத்வைத வேதாந்தம் என்ன கூறுகிறது?", en: "What does Advaita Vedanta state?" }, options: { ta: ["ஆன்மாவும் பிரம்மமும் ஒன்றே", "ஆன்மாவும் பிரம்மமும் வெவ்வேறானவை", "ஆன்மா பிரம்மத்தின் ஒரு பகுதி", "ஆன்மா இல்லை"], en: ["Soul and Brahman are one", "Soul and Brahman are different", "Soul is part of Brahman", "Soul doesn't exist"] }, answer: 0 },
      { question: { ta: "'தத் த்வம் அஸி' என்ற வாக்கியத்தின் பொருள் என்ன?", en: "What is the meaning of 'Tat Tvam Asi'?" }, options: { ta: ["நீயே அது", "நீ அதிலிருந்து வேறு", "அது பெரியது", "நீ சிறியவன்"], en: ["You are That", "You are different from That", "That is greater", "You are small"] }, answer: 0 },
      { question: { ta: "மாயா என்றால் என்ன?", en: "What is Maya?" }, options: { ta: ["இந்த உலகின் மாயை", "உண்மையான அறிவு", "தெய்வீக அருள்", "பிறப்பின் சுழற்சி"], en: ["The illusion of this world", "True knowledge", "Divine grace", "Cycle of birth"] }, answer: 0 },
      { question: { ta: "வேதாந்தத்தில் 'அவித்தியை' என்றால் என்ன?", en: "What is 'Avidya' in Vedanta?" }, options: { ta: ["அறியாமை", "அறிவு", "பக்தி", "செயல்"], en: ["Ignorance", "Knowledge", "Devotion", "Action"] }, answer: 0 },
      { question: { ta: "ஞான யோகா எதை வலியுறுத்துகிறது?", en: "What does Gnana Yoga emphasize?" }, options: { ta: ["அறிவு மற்றும் விவேகம்", "பக்தி மற்றும் வழிபாடு", "தன்னலமற்ற செயல்", "தியானம்"], en: ["Knowledge and discrimination", "Devotion and worship", "Selfless action", "Meditation"] }, answer: 0 },
      { question: { ta: "தர்சனம் என்றால் என்ன?", en: "What is Darshana?" }, options: { ta: ["தத்துவக் கண்ணோட்டம் அல்லது பார்வை", "ஒரு நடனம்", "ஒரு பண்டிகை", "ஒரு உணவு வகை"], en: ["Philosophical perspective or view", "A dance", "A festival", "A food item"] }, answer: 0 },
      { question: { ta: "இந்து தத்துவத்தின் ஆறு பாரம்பரிய பள்ளிகள் என்ன?", en: "What are the six traditional schools of Hindu philosophy?" }, options: { ta: ["சாங்கியம், யோகம், நியாயம், வைசேஷிகம், மீமாசை, வேதாந்தம்", "ஒன்று மட்டும்", "மூன்று மட்டும்", "நான்கு மட்டும்"], en: ["Samkhya, Yoga, Nyaya, Vaisheshika, Mimamsa, Vedanta", "Only one", "Only three", "Only four"] }, answer: 0 },
      { question: { ta: "சாங்கிய தத்துவத்தை உருவாக்கியவர் யார்?", en: "Who founded Samkhya philosophy?" }, options: { ta: ["கபிலர்", "பதஞ்சலி", "கௌதமர்", "கனாடர்"], en: ["Kapila", "Patanjali", "Gautama", "Kanada"] }, answer: 0 },
      { question: { ta: "யோக தத்துவத்தை உருவாக்கியவர் யார்?", en: "Who founded Yoga philosophy?" }, options: { ta: ["பதஞ்சலி", "கபிலர்", "கௌதமர்", "கனாடர்"], en: ["Patanjali", "Kapila", "Gautama", "Kanada"] }, answer: 0 },
      { question: { ta: "நியாய தத்துவம் எதைப் பற்றி ஆராய்கிறது?", en: "What does Nyaya philosophy investigate?" }, options: { ta: ["தர்க்கம் மற்றும் அறிவு கோட்பாடு", "பக்தி", "செயல்", "தியானம்"], en: ["Logic and theory of knowledge", "Devotion", "Action", "Meditation"] }, answer: 0 },
      { question: { ta: "வைசேஷிக தத்துவம் எதைப் பற்றி ஆராய்கிறது?", en: "What does Vaisheshika philosophy investigate?" }, options: { ta: ["இயற்கையின் கூறுகள் மற்றும் அணுக்கள்", "தர்க்கம் மட்டும்", "பக்தி மட்டும்", "செயல் மட்டும்"], en: ["Elements of nature and atoms", "Logic only", "Devotion only", "Action only"] }, answer: 0 },
      { question: { ta: "மீமாசை தத்துவம் எதைப் பற்றி ஆராய்கிறது?", en: "What does Mimamsa philosophy investigate?" }, options: { ta: ["வேத சடங்குகள் மற்றும் கர்மா", "வேதாந்தம்", "தர்க்கம்", "இயற்கை"], en: ["Vedic rituals and karma", "Vedanta", "Logic", "Nature"] }, answer: 0 },
    ],
  },
  // ── CATEGORY 7 ──
  {
    id: "yoga_meditation",
    title: { ta: "யோகா மற்றும் தியானம்", en: "Yoga & Meditation" },
    description: { ta: "பயிற்சிகள், ஆசனங்கள் மற்றும் தியான முறைகள்", en: "Practices, asanas and meditation techniques" },
    icon: "spa",
    color: "#2E7D32",
    questions: [
      { question: { ta: "யோகாவின் எட்டு அங்கங்கள் என்ன அழைக்கப்படுகின்றன?", en: "What are the eight limbs of Yoga called?" }, options: { ta: ["அஷ்டாங்க யோகா", "ஹத யோகா", "ராஜ யோகா", "குண்டலினி"], en: ["Ashtanga Yoga", "Hatha Yoga", "Raja Yoga", "Kundalini"] }, answer: 0 },
      { question: { ta: "யமம் என்றால் என்ன?", en: "What is Yama?" }, options: { ta: ["தார்மீக தடைகள்", "தார்மீக கட்டளைகள்", "உடல் பயிற்சி", "உயிர் சக்தி"], en: ["Moral restraints", "Moral observances", "Physical practice", "Life force"] }, answer: 0 },
      { question: { ta: "நியமம் என்றால் என்ன?", en: "What is Niyama?" }, options: { ta: ["தார்மீக கட்டளைகள்", "தார்மீக தடைகள்", "உடல் பயிற்சி", "தியானம்"], en: ["Moral observances", "Moral restraints", "Physical practice", "Meditation"] }, answer: 0 },
      { question: { ta: "ஆசனம் என்றால் என்ன?", en: "What is Asana?" }, options: { ta: ["யோகா தோரணை", "மூச்சுப் பயிற்சி", "தியானம்", "தார்மீக கட்டளை"], en: ["Yoga posture", "Breath practice", "Meditation", "Moral observance"] }, answer: 0 },
      { question: { ta: "பிராணாயாமம் என்றால் என்ன?", en: "What is Pranayama?" }, options: { ta: ["மூச்சுக் கட்டுப்பாடு", "தியானம்", "உடல் தோரணை", "தார்மீக கட்டளை"], en: ["Breath control", "Meditation", "Physical posture", "Moral observance"] }, answer: 0 },
      { question: { ta: "பிரத்யாஹாரம் என்றால் என்ன?", en: "What is Pratyahara?" }, options: { ta: ["புலன்களைத் திரும்பப் பெறுதல்", "தியானம்", "மூச்சுப் பயிற்சி", "உடல் தோரணை"], en: ["Withdrawal of senses", "Meditation", "Breath practice", "Physical posture"] }, answer: 0 },
      { question: { ta: "தாரணை என்றால் என்ன?", en: "What is Dharana?" }, options: { ta: ["ஒருமுகப்படுத்துதல்", "தியானம்", "சமாதி", "மூச்சுப் பயிற்சி"], en: ["Concentration", "Meditation", "Samadhi", "Breath practice"] }, answer: 0 },
      { question: { ta: "தியானம் என்றால் என்ன?", en: "What is Dhyana?" }, options: { ta: ["தியானம் (மன ஒருமை)", "ஒருமுகப்படுத்துதல்", "சமாதி", "உடல் தோரணை"], en: ["Meditation", "Concentration", "Samadhi", "Physical posture"] }, answer: 0 },
      { question: { ta: "சமாதி என்றால் என்ன?", en: "What is Samadhi?" }, options: { ta: ["ஆன்மீக உச்ச நிலை", "தியானம்", "ஒருமுகப்படுத்துதல்", "மூச்சுப் பயிற்சி"], en: ["Spiritual absorption", "Meditation", "Concentration", "Breath practice"] }, answer: 0 },
      { question: { ta: "ஹத யோகா எதை வலியுறுத்துகிறது?", en: "What does Hatha Yoga emphasize?" }, options: { ta: ["உடல் மற்றும் மன பயிற்சிகள்", "ஞானம் மட்டும்", "பக்தி மட்டும்", "சடங்குகள் மட்டும்"], en: ["Physical and mental practices", "Knowledge only", "Devotion only", "Rituals only"] }, answer: 0 },
      { question: { ta: "குண்டலினி என்றால் என்ன?", en: "What is Kundalini?" }, options: { ta: ["முதுகெலும்பின் அடியில் உள்ள சக்தி", "ஒரு யோகா தோரணை", "ஒரு மூச்சுப் பயிற்சி", "ஒரு தியான முறை"], en: ["Energy at the base of the spine", "A yoga posture", "A breath practice", "A meditation technique"] }, answer: 0 },
      { question: { ta: "சக்திகள் (சக்கரங்கள்) என்றால் என்ன?", en: "What are Chakras?" }, options: { ta: ["உடலில் உள்ள சக்தி மையங்கள்", "உடல் தோரணைகள்", "மூச்சுப் பயிற்சிகள்", "தியான முறைகள்"], en: ["Energy centers in the body", "Physical postures", "Breath practices", "Meditation techniques"] }, answer: 0 },
      { question: { ta: "சவாசனம் என்றால் என்ன?", en: "What is Savasana?" }, options: { ta: ["இறுதி ஓய்வு தோரணை", "ஒரு கடினமான தோரணை", "ஒரு மூச்சுப் பயிற்சி", "ஒரு தியான முறை"], en: ["Final relaxation posture", "A difficult posture", "A breath practice", "A meditation technique"] }, answer: 0 },
      { question: { ta: "சூரிய நமஸ்காரத்தில் எத்தனை தோரணைகள் உள்ளன?", en: "How many postures are there in Sun Salutation?" }, options: { ta: ["12", "5", "8", "15"], en: ["12", "5", "8", "15"] }, answer: 0 },
      { question: { ta: "மந்திர ஜபம் என்றால் என்ன?", en: "What is Mantra Japa?" }, options: { ta: ["புனித மந்திரத்தை மீண்டும் மீண்டும் கூறுதல்", "உடல் பயிற்சி", "மூச்சுப் பயிற்சி", "தியானம்"], en: ["Repetition of a sacred mantra", "Physical practice", "Breath practice", "Meditation"] }, answer: 0 },
    ],
  },
  // ── CATEGORY 8 ──
  {
    id: "bhakti",
    title: { ta: "பக்தி இயக்கம்", en: "Bhakti Movement" },
    description: { ta: "அடியார்கள், பாடல்கள் மற்றும் பக்தி பாரம்பரியம்", en: "Saints, hymns and devotional tradition" },
    icon: "favorite",
    color: "#C62828",
    questions: [
      { question: { ta: "ஆழ்வார்கள் எத்தனை பேர்?", en: "How many Azhwars are there?" }, options: { ta: ["12", "10", "8", "15"], en: ["12", "10", "8", "15"] }, answer: 0 },
      { question: { ta: "நாயன்மார்கள் எத்தனை பேர்?", en: "How many Nayanmars are there?" }, options: { ta: ["63", "50", "40", "70"], en: ["63", "50", "40", "70"] }, answer: 0 },
      { question: { ta: "பெரியாழ்வார் என்று அழைக்கப்படுபவர் யார்?", en: "Who is known as Periyalvar?" }, options: { ta: ["விஷ்ணுசித்தர்", "திருப்பாணாழ்வார்", "நம்மாழ்வார்", "ஆண்டாள்"], en: ["Vishnuchittar", "Thiruppanalvar", "Nammalvar", "Andal"] }, answer: 0 },
      { question: { ta: "ஆண்டாள் எந்தக் கடவுளின் பக்தை?", en: "Andal is a devotee of which deity?" }, options: { ta: ["விஷ்ணு", "சிவன்", "முருகன்", "விநாயகர்"], en: ["Vishnu", "Shiva", "Murugan", "Vinayagar"] }, answer: 0 },
      { question: { ta: "மணிவாசகர் இயற்றிய நூல் எது?", en: "Which text was composed by Manivachakar?" }, options: { ta: ["திருவாசகம்", "தேவாரம்", "திவ்விய பிரபந்தம்", "பெரிய புராணம்"], en: ["Thiruvasagam", "Thevaram", "Divya Prabandham", "Periya Puranam"] }, answer: 0 },
      { question: { ta: "தேவாரத்தை இயற்றிய மூவர் யார்?", en: "Who are the three who composed Thevaram?" }, options: { ta: ["அப்பர், சம்பந்தர், சுந்தரர்", "மணிவாசகர், அப்பர், சம்பந்தர்", "சுந்தரர், மணிவாசகர், அப்பர்", "சம்பந்தர், மணிவாசகர், சுந்தரர்"], en: ["Appar, Sambandar, Sundarar", "Manivachakar, Appar, Sambandar", "Sundarar, Manivachakar, Appar", "Sambandar, Manivachakar, Sundarar"] }, answer: 0 },
      { question: { ta: "திவ்விய பிரபந்தத்தைத் தொகுத்தவர் யார்?", en: "Who compiled the Divya Prabandham?" }, options: { ta: ["நாதமுனிகள்", "ராமானுஜர்", "வியாசர்", "வால்மீகி"], en: ["Nathamuni", "Ramanuja", "Vyasa", "Valmiki"] }, answer: 0 },
      { question: { ta: "எந்த நாயன்மார் 'திருநாவுக்கரசர்' என்றும் அழைக்கப்படுகிறார்?", en: "Which Nayanmar is also called 'Thirunavukkarasar'?" }, options: { ta: ["அப்பர்", "சம்பந்தர்", "சுந்தரர்", "மணிவாசகர்"], en: ["Appar", "Sambandar", "Sundarar", "Manivachakar"] }, answer: 0 },
      { question: { ta: "எந்த நாயன்மார் 'திருஞானசம்பந்தர்' என்றும் அழைக்கப்படுகிறார்?", en: "Which Nayanmar is also called 'Thirugnanasambandar'?" }, options: { ta: ["சம்பந்தர்", "அப்பர்", "சுந்தரர்", "மணிவாசகர்"], en: ["Sambandar", "Appar", "Sundarar", "Manivachakar"] }, answer: 0 },
      { question: { ta: "திருப்புகழ் எந்தக் கடவுளுக்கு அர்ப்பணிக்கப்பட்டது?", en: "Thiruppugazh is dedicated to which deity?" }, options: { ta: ["முருகன்", "சிவன்", "விஷ்ணு", "விநாயகர்"], en: ["Murugan", "Shiva", "Vishnu", "Vinayagar"] }, answer: 0 },
      { question: { ta: "அருணகிரிநாதர் இயற்றிய நூல் எது?", en: "Which text was composed by Arunagirinathar?" }, options: { ta: ["திருப்புகழ்", "திருவாசகம்", "தேவாரம்", "பெரிய புராணம்"], en: ["Thiruppugazh", "Thiruvasagam", "Thevaram", "Periya Puranam"] }, answer: 0 },
      { question: { ta: "பெரிய புராணத்தை இயற்றியவர் யார்?", en: "Who composed the Periya Puranam?" }, options: { ta: ["சேக்கிழார்", "மணிவாசகர்", "அப்பர்", "சம்பந்தர்"], en: ["Sekkizhar", "Manivachakar", "Appar", "Sambandar"] }, answer: 0 },
      { question: { ta: "காரைக்கால் அம்மையார் எந்தக் கடவுளின் பக்தை?", en: "Karaikkal Ammaiyar is a devotee of which deity?" }, options: { ta: ["சிவன்", "விஷ்ணு", "முருகன்", "விநாயகர்"], en: ["Shiva", "Vishnu", "Murugan", "Vinayagar"] }, answer: 0 },
      { question: { ta: "தாயுமானவர் எந்தக் காலத்தில் வாழ்ந்தார்?", en: "In which period did Thayumanavar live?" }, options: { ta: ["18ம் நூற்றாண்டு", "15ம் நூற்றாண்டு", "12ம் நூற்றாண்டு", "20ம் நூற்றாண்டு"], en: ["18th century", "15th century", "12th century", "20th century"] }, answer: 0 },
      { question: { ta: "இந்து பக்தி இயக்கம் எப்போது தொடங்கியது?", en: "When did the Hindu Bhakti movement begin?" }, options: { ta: ["6-9ம் நூற்றாண்டுகளில்", "12ம் நூற்றாண்டில்", "15ம் நூற்றாண்டில்", "18ம் நூற்றாண்டில்"], en: ["6-9th centuries", "12th century", "15th century", "18th century"] }, answer: 0 },
    ],
  },
  // ── CATEGORY 9 ──
  {
    id: "symbols_rituals",
    title: { ta: "சின்னங்கள் மற்றும் சடங்குகள்", en: "Symbols & Rituals" },
    description: { ta: "புனித சின்னங்கள், சடங்குகள் மற்றும் பழக்கவழக்கங்கள்", en: "Sacred symbols, rituals and customs" },
    icon: "gesture",
    color: "#6A1B9A",
    questions: [
      { question: { ta: "திலகம் என்றால் என்ன?", en: "What is Tilakam?" }, options: { ta: ["நெற்றியில் இடப்படும் புனித அடையாளம்", "ஒரு ஆடை", "ஒரு உணவு", "ஒரு கருவி"], en: ["Sacred mark on the forehead", "A garment", "A food", "A tool"] }, answer: 0 },
      { question: { ta: "குங்குமத்தின் நிறம் என்ன?", en: "What is the color of Kumkum?" }, options: { ta: ["சிவப்பு", "மஞ்சள்", "வெள்ளை", "நீலம்"], en: ["Red", "Yellow", "White", "Blue"] }, answer: 0 },
      { question: { ta: "சந்தனம் எதற்காகப் பயன்படுத்தப்படுகிறது?", en: "What is Sandalwood used for?" }, options: { ta: ["புனித பூச்சு மற்றும் நறுமணத்திற்காக", "உணவிற்காக", "ஆடைக்காக", "கருவிகளுக்காக"], en: ["Sacred paste and fragrance", "Food", "Clothing", "Tools"] }, answer: 0 },
      { question: { ta: "விபூதி எதன் அடையாளம்?", en: "What is Vibhooti a symbol of?" }, options: { ta: ["சிவனின் பக்தி", "விஷ்ணுவின் பக்தி", "செல்வம்", "கல்வி"], en: ["Devotion to Shiva", "Devotion to Vishnu", "Wealth", "Education"] }, answer: 0 },
      { question: { ta: "புனித நூல் (உபநீதம்) என்றால் என்ன?", en: "What is the sacred thread (Upanayana)?" }, options: { ta: ["ஒரு ஆரம்ப சடங்கு", "ஒரு திருமணம்", "ஒரு இறுதி சடங்கு", "ஒரு திருவிழா"], en: ["An initiation ritual", "A marriage", "A funeral", "A festival"] }, answer: 0 },
      { question: { ta: "திருமணத்தின் போது சப்தபதி என்றால் என்ன?", en: "What is Saptapadi during marriage?" }, options: { ta: ["ஏழு அடிகள் சேர்ந்து நடத்தல்", "ஏழு மந்திரங்கள்", "ஏழு நாட்கள்", "ஏழு காணிக்கைகள்"], en: ["Walking seven steps together", "Seven mantras", "Seven days", "Seven offerings"] }, answer: 0 },
      { question: { ta: "எந்த விலங்கு தெய்வீகத்தின் அடையாளமாகக் கருதப்படுகிறது?", en: "Which animal is considered a symbol of divinity?" }, options: { ta: ["பசு", "குதிரை", "ஒட்டகம்", "நாய்"], en: ["Cow", "Horse", "Camel", "Dog"] }, answer: 0 },
      { question: { ta: "தாமரை எதன் அடையாளம்?", en: "What is the lotus a symbol of?" }, options: { ta: ["தெய்வீக அழகு மற்றும் புனிதம்", "செல்வம்", "வலிமை", "விரைவு"], en: ["Divine beauty and purity", "Wealth", "Strength", "Speed"] }, answer: 0 },
      { question: { ta: "மங்களாசாஸனம் என்றால் என்ன?", en: "What is Mangalasasanam?" }, options: { ta: ["ஆசீர்வாதப் பாடல்", "ஒரு திருவிழா", "ஒரு சடங்கு", "ஒரு காணிக்கை"], en: ["Blessing song", "A festival", "A ritual", "An offering"] }, answer: 0 },
      { question: { ta: "காலை மற்றும் மாலை பூஜை என்ன அழைக்கப்படுகிறது?", en: "What are morning and evening worship called?" }, options: { ta: ["சந்தியா வந்தனம்", "ஆரத்தி", "பிரதக்ஷிணம்", "தீபாராதனை"], en: ["Sandhya Vandanam", "Aarti", "Pradakshina", "Deeparadhana"] }, answer: 0 },
      { question: { ta: "ஹோமம் என்றால் என்ன?", en: "What is Homam?" }, options: { ta: ["ஒரு தீ சடங்கு", "ஒரு திருவிழா", "ஒரு இறுதி சடங்கு", "ஒரு திருமணம்"], en: ["A fire ritual", "A festival", "A funeral", "A wedding"] }, answer: 0 },
      { question: { ta: "தர்பை புல்லின் முக்கியத்துவம் என்ன?", en: "What is the significance of Darbha grass?" }, options: { ta: ["சடங்குகளில் புனிதமாகப் பயன்படுகிறது", "உணவாகப் பயன்படுகிறது", "ஆடையாகப் பயன்படுகிறது", "கருவியாகப் பயன்படுகிறது"], en: ["Used as sacred in rituals", "Used as food", "Used as clothing", "Used as tool"] }, answer: 0 },
      { question: { ta: "சங்கு எதற்குப் பயன்படுத்தப்படுகிறது?", en: "What is the conch shell used for?" }, options: { ta: ["சடங்குகளில் ஊதுவதற்கு", "உணவிற்கு", "அலங்காரத்திற்கு", "ஆயுதமாக"], en: ["Blowing during rituals", "Food", "Decoration", "Weapon"] }, answer: 0 },
      { question: { ta: "மணியின் முக்கியத்துவம் என்ன?", en: "What is the significance of the bell?" }, options: { ta: ["தீயவற்றை விரட்டவும் இறைவனை அழைக்கவும்", "இசைக்கு", "அலங்காரத்திற்கு", "பரிசுக்கு"], en: ["To ward off evil and invoke the divine", "Music", "Decoration", "Gift"] }, answer: 0 },
      { question: { ta: "சடங்கு பாத்திரங்களை புனிதப்படுத்தும் சடங்கு என்ன?", en: "What is the ritual of purifying ritual vessels called?" }, options: { ta: ["ப்ரோக்ஷணம்", "ஆரத்தி", "பிரதக்ஷிணம்", "ஹோமம்"], en: ["Prokshanam", "Aarti", "Pradakshina", "Homam"] }, answer: 0 },
    ],
  },
  // ── CATEGORY 10 ──
  {
    id: "ramayana",
    title: { ta: "ராமாயணம்", en: "Ramayana" },
    description: { ta: "ராமாயணத்தின் கதை, பாத்திரங்கள் மற்றும் போதனைகள்", en: "Story, characters and teachings of Ramayana" },
    icon: "history-edu",
    color: "#D84315",
    questions: [
      { question: { ta: "ராமாயணத்தின் ஆசிரியர் யார்?", en: "Who is the author of Ramayana?" }, options: { ta: ["வால்மீகி", "வியாசர்", "காளிதாசர்", "துளசிதாஸ்"], en: ["Valmiki", "Vyasa", "Kalidasa", "Tulsidas"] }, answer: 0 },
      { question: { ta: "ராமரின் தந்தை யார்?", en: "Who is Rama's father?" }, options: { ta: ["தசரதர்", "வசிஷ்டர்", "விஷ்வாமித்திரர்", "ஜனகர்"], en: ["Dasharatha", "Vashishta", "Vishwamitra", "Janaka"] }, answer: 0 },
      { question: { ta: "ராமரின் தாய் யார்?", en: "Who is Rama's mother?" }, options: { ta: ["கௌசல்யை", "கைகேயி", "சுமித்திரை", "சீதை"], en: ["Kausalya", "Kaikeyi", "Sumitra", "Sita"] }, answer: 0 },
      { question: { ta: "ராமர் எவ்வளவு காலம் வனவாசம் செய்தார்?", en: "How many years did Rama spend in exile?" }, options: { ta: ["14", "12", "10", "16"], en: ["14", "12", "10", "16"] }, answer: 0 },
      { question: { ta: "இலங்கைக்கு செல்ல ராமர் கட்டிய பாலம் எது?", en: "Which bridge did Rama build to go to Lanka?" }, options: { ta: ["ராமசேது", "அடம்ஸ் பாலம்", "கோதாவரி பாலம்", "கங்கை பாலம்"], en: ["Ramasethu", "Adam's Bridge", "Godavari Bridge", "Ganges Bridge"] }, answer: 0 },
      { question: { ta: "ராமரின் பிரதான ஆயுதம் எது?", en: "What is Rama's primary weapon?" }, options: { ta: ["வில் மற்றும் அம்பு", "வாள்", "கதை", "சக்கரம்"], en: ["Bow and arrow", "Sword", "Mace", "Discus"] }, answer: 0 },
      { question: { ta: "ராமர் எந்த நகரத்தின் அரசராக இருந்தார்?", en: "Which city's king was Rama?" }, options: { ta: ["அயோத்தி", "மதுரா", "இலங்கை", "துவாரகா"], en: ["Ayodhya", "Mathura", "Lanka", "Dwaraka"] }, answer: 0 },
      { question: { ta: "ராவணனின் தம்பி யார்?", en: "Who is Ravana's younger brother?" }, options: { ta: ["விபீஷணன்", "கும்பகர்ணன்", "இந்திரஜித்", "மேகநாதன்"], en: ["Vibhishana", "Kumbhakarna", "Indrajit", "Meghanada"] }, answer: 0 },
      { question: { ta: "இலங்கையில் ராவணனின் தலைநகரம் எது?", en: "What is Ravana's capital in Lanka?" }, options: { ta: ["இலங்காபுரி", "ஸ்ரீநகர்", "துவாரகா", "அயோத்தி"], en: ["Lankapuri", "Srinagar", "Dwaraka", "Ayodhya"] }, answer: 0 },
      { question: { ta: "ராமருக்கு உதவிய வானர தலைவர் யார்?", en: "Who is the monkey king who helped Rama?" }, options: { ta: ["சுக்ரீவன்", "வாலி", "அனுமன்", "ஜாம்பவான்"], en: ["Sugriva", "Vali", "Hanuman", "Jambavan"] }, answer: 0 },
      { question: { ta: "சீதையை கடத்தியவர் யார்?", en: "Who abducted Sita?" }, options: { ta: ["ராவணன்", "கும்பகர்ணன்", "விபீஷணன்", "இந்திரஜித்"], en: ["Ravana", "Kumbhakarna", "Vibhishana", "Indrajit"] }, answer: 0 },
      { question: { ta: "ராவணனை யார் கொன்றார்?", en: "Who killed Ravana?" }, options: { ta: ["ராமர்", "லட்சுமணர்", "அனுமன்", "விபீஷணன்"], en: ["Rama", "Lakshmana", "Hanuman", "Vibhishana"] }, answer: 0 },
      { question: { ta: "ராமரின் சகோதரர் யார்?", en: "Who is Rama's brother?" }, options: { ta: ["லட்சுமணர்", "பரதர்", "சத்ருக்னன்", "அனைத்தும்"], en: ["Lakshmana", "Bharata", "Shatrughna", "All of these"] }, answer: 3 },
      { question: { ta: "சீதை யாருடைய மகள்?", en: "Whose daughter is Sita?" }, options: { ta: ["ஜனகர்", "தசரதர்", "வசிஷ்டர்", "விஷ்வாமித்திரர்"], en: ["Janaka", "Dasharatha", "Vashishta", "Vishwamitra"] }, answer: 0 },
      { question: { ta: "ராமர் வனவாசத்தை முடித்து திரும்பிய பண்டிகை எது?", en: "Which festival celebrates Rama's return after exile?" }, options: { ta: ["தீபாவளி", "ராம நவமி", "விஜயதசமி", "பொங்கல்"], en: ["Deepavali", "Rama Navami", "Vijayadashami", "Pongal"] }, answer: 0 },
    ],
  },
  // ── CATEGORY 11 ──
  {
    id: "mahabharata",
    title: { ta: "மகாபாரதம்", en: "Mahabharata" },
    description: { ta: "மகாபாரதத்தின் கதை, போர் மற்றும் கீதை", en: "Story, war and Gita of Mahabharata" },
    icon: "history",
    color: "#C62828",
    questions: [
      { question: { ta: "மகாபாரதத்தின் ஆசிரியர் யார்?", en: "Who is the author of Mahabharata?" }, options: { ta: ["வியாசர்", "வால்மீகி", "காளிதாசர்", "துளசிதாஸ்"], en: ["Vyasa", "Valmiki", "Kalidasa", "Tulsidas"] }, answer: 0 },
      { question: { ta: "மகாபாரதத்தில் எத்தனை பர்வங்கள் உள்ளன?", en: "How many parvas are there in Mahabharata?" }, options: { ta: ["18", "12", "15", "20"], en: ["18", "12", "15", "20"] }, answer: 0 },
      { question: { ta: "பாண்டவர்களின் தாய் யார்?", en: "Who is the mother of the Pandavas?" }, options: { ta: ["குந்தி", "காந்தாரி", "திரௌபதி", "சுபத்ரா"], en: ["Kunti", "Gandhari", "Draupadi", "Subhadra"] }, answer: 0 },
      { question: { ta: "கௌரவர்களின் தந்தை யார்?", en: "Who is the father of the Kauravas?" }, options: { ta: ["திருதராஷ்டிரர்", "பாண்டு", "விதுரர்", "பீஷ்மர்"], en: ["Dhritarashtra", "Pandu", "Vidura", "Bhishma"] }, answer: 0 },
      { question: { ta: "பீஷ்மரின் உண்மையான பெயர் என்ன?", en: "What is Bhishma's real name?" }, options: { ta: ["தேவவிரதர்", "சந்தனு", "பிரதீப்", "சுமந்தர்"], en: ["Devavrata", "Shantanu", "Prateep", "Sumanta"] }, answer: 0 },
      { question: { ta: "குருஷேத்திரப் போர் எத்தனை நாட்கள் நடந்தது?", en: "How many days did the Kurukshetra war last?" }, options: { ta: ["18", "12", "10", "15"], en: ["18", "12", "10", "15"] }, answer: 0 },
      { question: { ta: "அர்ஜுனனின் தேரோட்டி யார்?", en: "Who is Arjuna's charioteer?" }, options: { ta: ["கிருஷ்ணர்", "நாரதர்", "பலராமர்", "உத்யோகர்"], en: ["Krishna", "Narada", "Balarama", "Udyoga"] }, answer: 0 },
      { question: { ta: "திரௌபதியின் ஐந்து கணவர்கள் யார்?", en: "Who are Draupadi's five husbands?" }, options: { ta: ["பாண்டவர்கள்", "கௌரவர்கள்", "விருஷ்ணிகள்", "யாதவர்கள்"], en: ["Pandavas", "Kauravas", "Vrishnis", "Yadavas"] }, answer: 0 },
      { question: { ta: "கௌரவர்களில் மூத்தவர் யார்?", en: "Who is the eldest among the Kauravas?" }, options: { ta: ["துரியோதனன்", "துச்சாதனன்", "விகர்ணன்", "யுயுத்சு"], en: ["Duryodhana", "Dushasana", "Vikarna", "Yuyutsu"] }, answer: 0 },
      { question: { ta: "பீஷ்மர் யாருடைய ஆசீர்வாதத்துடன் இறக்க விரும்பினார்?", en: "With whose blessing did Bhishma wish to die?" }, options: { ta: ["சூரியனுடைய", "பித்ருக்களுடைய", "கிருஷ்ணருடைய", "துரியோதனனுடைய"], en: ["Surya's", "Pitrs'", "Krishna's", "Duryodhana's"] }, answer: 0 },
      { question: { ta: "பாண்டவர்களில் மூத்தவர் யார்?", en: "Who is the eldest among the Pandavas?" }, options: { ta: ["தருமர்", "பீமன்", "அர்ஜுனன்", "நகுலன்"], en: ["Yudhishthira", "Bhima", "Arjuna", "Nakula"] }, answer: 0 },
      { question: { ta: "கிருஷ்ணர் கீதையை யாருக்கு உபதேசித்தார்?", en: "To whom did Krishna preach the Gita?" }, options: { ta: ["அர்ஜுனன்", "தருமர்", "பீமன்", "விதுரர்"], en: ["Arjuna", "Yudhishthira", "Bhima", "Vidura"] }, answer: 0 },
      { question: { ta: "பாண்டவர்களின் தாய் குந்தியின் மற்றொரு பெயர் என்ன?", en: "What is another name of Kunti, the Pandavas' mother?" }, options: { ta: ["பிருதை", "காந்தாரி", "திரௌபதி", "சுபத்ரா"], en: ["Pritha", "Gandhari", "Draupadi", "Subhadra"] }, answer: 0 },
      { question: { ta: "குருஷேத்திரப் போரில் வெற்றி பெற்றவர் யார்?", en: "Who won the Kurukshetra war?" }, options: { ta: ["பாண்டவர்கள்", "கௌரவர்கள்", "உத்தரர்கள்", "சிந்து மன்னர்கள்"], en: ["Pandavas", "Kauravas", "Uttaras", "Sindhu kings"] }, answer: 0 },
      { question: { ta: "பீஷ்மரின் மற்றொரு பெயர் என்ன?", en: "What is another name of Bhishma?" }, options: { ta: ["கங்காபுத்திரர்", "தேவவிரதர்", "சந்தனு", "பிரதீப்"], en: ["Gangaputra", "Devavrata", "Shantanu", "Prateep"] }, answer: 1 },
    ],
  },
  // ── CATEGORY 12 ──
  {
    id: "bhagavad_gita",
    title: { ta: "பகவத் கீதை", en: "Bhagavad Gita" },
    description: { ta: "கீதையின் போதனைகள், கர்மா, ஞானம், பக்தி", en: "Teachings, Karma, Gnana, Bhakti" },
    icon: "book",
    color: "#2E7D32",
    questions: [
      { question: { ta: "கீதை எத்தனை அத்தியாயங்களைக் கொண்டுள்ளது?", en: "How many chapters does the Gita have?" }, options: { ta: ["18", "12", "15", "20"], en: ["18", "12", "15", "20"] }, answer: 0 },
      { question: { ta: "கீதையில் எத்தனை ஸ்லோகங்கள் உள்ளன?", en: "How many verses are there in the Gita?" }, options: { ta: ["700", "500", "1000", "800"], en: ["700", "500", "1000", "800"] }, answer: 0 },
      { question: { ta: "கீதையின் முக்கிய செய்தி என்ன?", en: "What is the main message of the Gita?" }, options: { ta: ["கர்மா, ஞானம், பக்தி", "யாகம் மட்டும்", "தானம் மட்டும்", "தவம் மட்டும்"], en: ["Karma, Gnana, Bhakti", "Sacrifice only", "Charity only", "Penance only"] }, answer: 0 },
      { question: { ta: "கீதையில் கிருஷ்ணர் எந்த யோகத்தை வலியுறுத்துகிறார்?", en: "Which yoga does Krishna emphasize in the Gita?" }, options: { ta: ["கர்ம யோகம்", "ஞான யோகம்", "பக்தி யோகம்", "அனைத்தும்"], en: ["Karma Yoga", "Gnana Yoga", "Bhakti Yoga", "All of these"] }, answer: 3 },
      { question: { ta: "'யோகஸ்த குரு கர்மானி' என்றால் என்ன?", en: "What does 'Yogastha Kuru Karmani' mean?" }, options: { ta: ["யோகத்தில் நின்று கர்மா செய்", "யோகம் செய்", "கர்மாவை விட்டுவிடு", "தியானம் செய்"], en: ["Established in yoga, perform actions", "Do yoga", "Give up karma", "Meditate"] }, answer: 0 },
      { question: { ta: "கீதை எந்த மொழியில் எழுதப்பட்டது?", en: "In which language was the Gita written?" }, options: { ta: ["சமஸ்கிருதம்", "தமிழ்", "இந்தி", "கன்னடம்"], en: ["Sanskrit", "Tamil", "Hindi", "Kannada"] }, answer: 0 },
      { question: { ta: "கீதையை வேறு எந்தப் பெயரில் அழைக்கலாம்?", en: "What is another name for the Gita?" }, options: { ta: ["கீதோபநிஷத்", "பகவத்கீதா", "உபநிஷத்", "அனைத்தும்"], en: ["Gitopanishad", "Bhagavadgita", "Upanishad", "All of these"] }, answer: 3 },
      { question: { ta: "கிருஷ்ணரின் பிறப்பு எந்த இடத்தில்?", en: "Where was Krishna born?" }, options: { ta: ["மதுரா", "துவாரகா", "விரிந்தாவனம்", "அயோத்தி"], en: ["Mathura", "Dwaraka", "Vrindavan", "Ayodhya"] }, answer: 0 },
      { question: { ta: "கீதையில் 'ஸ்திதப்ரஞ்ஞன்' என்றால் என்ன?", en: "What does 'Sthitaprajna' mean in the Gita?" }, options: { ta: ["நிலையான அறிவு உள்ளவன்", "பக்தி மிக்கவன்", "ஞானி", "யோகி"], en: ["One with steady wisdom", "Devotee", "Wise one", "Yogi"] }, answer: 0 },
      { question: { ta: "கீதையில் 'லோகஸங்க்ரஹம்' என்றால் என்ன?", en: "What does 'Lokasangraha' mean in the Gita?" }, options: { ta: ["உலக நலன்", "உலக இன்பம்", "உலக அறிவு", "உலக சக்தி"], en: ["Welfare of the world", "Worldly pleasure", "Worldly knowledge", "Worldly power"] }, answer: 0 },
      { question: { ta: "கீதையின் முதல் வசனம் யாரால் சொல்லப்பட்டது?", en: "Who spoke the first verse of the Gita?" }, options: { ta: ["திருதராஷ்டிரர்", "கிருஷ்ணர்", "அர்ஜுனன்", "வியாசர்"], en: ["Dhritarashtra", "Krishna", "Arjuna", "Vyasa"] }, answer: 0 },
      { question: { ta: "கீதையின் கடைசி வசனம் யாரால் சொல்லப்பட்டது?", en: "Who spoke the last verse of the Gita?" }, options: { ta: ["கிருஷ்ணர்", "அர்ஜுனன்", "தருமர்", "பீஷ்மர்"], en: ["Krishna", "Arjuna", "Yudhishthira", "Bhishma"] }, answer: 0 },
      { question: { ta: "கீதையில் பக்தியின் முக்கியத்துவம் என்ன?", en: "What is the importance of Bhakti in the Gita?" }, options: { ta: ["உயர்ந்த பாதை", "குறைந்த பாதை", "நடுத்தர பாதை", "தவறான பாதை"], en: ["Highest path", "Lowest path", "Middle path", "Wrong path"] }, answer: 0 },
      { question: { ta: "கீதையில் 'அகிம்சை' பற்றி என்ன கூறப்பட்டுள்ளது?", en: "What is said about 'Ahimsa' in the Gita?" }, options: { ta: ["அகிம்சை உயர்ந்த நற்பண்பு", "அகிம்சை தேவையில்லை", "அகிம்சை பலவீனம்", "அகிம்சை மட்டும் போதும்"], en: ["Non-violence is a virtue", "Non-violence is not needed", "Non-violence is weakness", "Only non-violence is enough"] }, answer: 0 },
      { question: { ta: "கீதையின் மற்றொரு பெயர் என்ன?", en: "What is another name of the Gita?" }, options: { ta: ["கீதா சாஸ்திரம்", "பகவத்கீதா", "யோக சாஸ்திரம்", "அனைத்தும்"], en: ["Gita Shastra", "Bhagavadgita", "Yoga Shastra", "All of these"] }, answer: 3 },
    ],
  },
  // ── CATEGORY 13 ──
  {
    id: "vedas_upanishads",
    title: { ta: "வேதங்கள் மற்றும் உபநிடதங்கள்", en: "Vedas & Upanishads" },
    description: { ta: "வேதங்கள், உபநிடதங்கள் மற்றும் அதன் தத்துவங்கள்", en: "Vedas, Upanishads and their philosophies" },
    icon: "auto-stories",
    color: "#4A148C",
    questions: [
      { question: { ta: "வேதங்கள் எவை?", en: "What are the Vedas?" }, options: { ta: ["பழமையான புனித நூல்கள்", "நவீன புத்தகங்கள்", "வரலாற்று குறிப்புகள்", "காவியங்கள்"], en: ["Ancient sacred texts", "Modern books", "Historical notes", "Epics"] }, answer: 0 },
      { question: { ta: "மொத்த வேதங்கள் எத்தனை?", en: "How many Vedas are there in total?" }, options: { ta: ["4", "3", "5", "6"], en: ["4", "3", "5", "6"] }, answer: 0 },
      { question: { ta: "வேதங்களின் பிரிவுகள் யாவை?", en: "What are the divisions of the Vedas?" }, options: { ta: ["சம்ஹிதை, பிராமணம், ஆரண்யகம், உபநிடதம்", "ஒன்று மட்டும்", "இரண்டு மட்டும்", "மூன்று மட்டும்"], en: ["Samhita, Brahmana, Aranyaka, Upanishad", "Only one", "Only two", "Only three"] }, answer: 0 },
      { question: { ta: "உபநிடதங்கள் எதைப் பற்றி பேசுகின்றன?", en: "What do the Upanishads discuss?" }, options: { ta: ["தத்துவம் மற்றும் ஆன்மீகம்", "சடங்குகள்", "வரலாறு", "அரசியல்"], en: ["Philosophy and spirituality", "Rituals", "History", "Politics"] }, answer: 0 },
      { question: { ta: "முக்கிய உபநிடதங்கள் எத்தனை?", en: "How many principal Upanishads are there?" }, options: { ta: ["13", "10", "15", "20"], en: ["13", "10", "15", "20"] }, answer: 0 },
      { question: { ta: "'அஹம் பிரம்மாஸ்மி' எந்த உபநிடதத்தில் உள்ளது?", en: "In which Upanishad is 'Aham Brahmasmi' found?" }, options: { ta: ["ப்ருஹதாரண்யக உபநிடதம்", "சாந்தோக்ய உபநிடதம்", "தைத்திரிய உபநிடதம்", "முண்டக உபநிடதம்"], en: ["Brihadaranyaka Upanishad", "Chandogya Upanishad", "Taittiriya Upanishad", "Mundaka Upanishad"] }, answer: 0 },
      { question: { ta: "'தத் த்வம் அஸி' எந்த உபநிடதத்தில் உள்ளது?", en: "In which Upanishad is 'Tat Tvam Asi' found?" }, options: { ta: ["சாந்தோக்ய உபநிடதம்", "ப்ருஹதாரண்யகம்", "கட உபநிடதம்", "ஐதரேயம்"], en: ["Chandogya Upanishad", "Brihadaranyaka", "Katha Upanishad", "Aitareya"] }, answer: 0 },
      { question: { ta: "ரிக் வேதம் எதைப் பற்றியது?", en: "What is the Rig Veda about?" }, options: { ta: ["பாடல்கள் மற்றும் மந்திரங்கள்", "சடங்குகள்", "வரலாறு", "இசை"], en: ["Hymns and mantras", "Rituals", "History", "Music"] }, answer: 0 },
      { question: { ta: "சாம வேதம் எதைப் பற்றியது?", en: "What is the Sama Veda about?" }, options: { ta: ["இசை மற்றும் மந்திரங்கள்", "சடங்குகள்", "கட்டிடக்கலை", "மருத்துவம்"], en: ["Music and mantras", "Rituals", "Architecture", "Medicine"] }, answer: 0 },
      { question: { ta: "யஜுர் வேதம் எதைப் பற்றியது?", en: "What is the Yajur Veda about?" }, options: { ta: ["யாக சடங்குகள்", "பாடல்கள்", "இசை", "தத்துவம்"], en: ["Sacrificial rituals", "Hymns", "Music", "Philosophy"] }, answer: 0 },
      { question: { ta: "அதர்வண வேதம் எதைப் பற்றியது?", en: "What is the Atharva Veda about?" }, options: { ta: ["மந்திரங்கள் மற்றும் மருத்துவம்", "சடங்குகள்", "இசை", "தத்துவம்"], en: ["Mantras and medicine", "Rituals", "Music", "Philosophy"] }, answer: 0 },
      { question: { ta: "வேதாந்தம் என்றால் என்ன?", en: "What is Vedanta?" }, options: { ta: ["வேதங்களின் முடிவு", "வேதங்களின் ஆரம்பம்", "வேதங்களின் நடு", "வேதங்கள் அல்ல"], en: ["End of the Vedas", "Beginning of the Vedas", "Middle of the Vedas", "Not the Vedas"] }, answer: 0 },
      { question: { ta: "உபநிடதங்களின் மொத்த எண்ணிக்கை எத்தனை?", en: "How many Upanishads are there in total?" }, options: { ta: ["108", "50", "100", "150"], en: ["108", "50", "100", "150"] }, answer: 0 },
      { question: { ta: "ப்ருஹதாரண்யக உபநிடதம் எதைப் பற்றியது?", en: "What is the Brihadaranyaka Upanishad about?" }, options: { ta: ["தத்துவம் மற்றும் ஆத்மா", "சடங்குகள்", "வரலாறு", "இசை"], en: ["Philosophy and soul", "Rituals", "History", "Music"] }, answer: 0 },
      { question: { ta: "வேதங்கள் எந்த மொழியில் உள்ளன?", en: "In which language are the Vedas?" }, options: { ta: ["வேத சமஸ்கிருதம்", "தமிழ்", "இந்தி", "பிராகிருதம்"], en: ["Vedic Sanskrit", "Tamil", "Hindi", "Prakrit"] }, answer: 0 },
    ],
  },
  // ── CATEGORY 14 ──
  {
    id: "puranas",
    title: { ta: "புராணங்கள்", en: "Puranas" },
    description: { ta: "புராணங்களின் கதைகள் மற்றும் பாரம்பரியம்", en: "Stories and traditions of the Puranas" },
    icon: "library-books",
    color: "#D84315",
    questions: [
      { question: { ta: "மொத்த புராணங்கள் எத்தனை?", en: "How many Puranas are there in total?" }, options: { ta: ["18", "12", "15", "20"], en: ["18", "12", "15", "20"] }, answer: 0 },
      { question: { ta: "முக்கிய புராணங்கள் எத்தனை?", en: "How many major Puranas are there?" }, options: { ta: ["18", "12", "15", "20"], en: ["18", "12", "15", "20"] }, answer: 0 },
      { question: { ta: "பாகவத புராணம் யாரைப் பற்றியது?", en: "Who is the Bhagavata Purana about?" }, options: { ta: ["விஷ்ணு", "சிவன்", "பிரம்மா", "சூரியன்"], en: ["Vishnu", "Shiva", "Brahma", "Surya"] }, answer: 0 },
      { question: { ta: "சிவ புராணம் யாரைப் பற்றியது?", en: "Who is the Shiva Purana about?" }, options: { ta: ["சிவன்", "விஷ்ணு", "பிரம்மா", "கணேசர்"], en: ["Shiva", "Vishnu", "Brahma", "Ganesha"] }, answer: 0 },
      { question: { ta: "விஷ்ணு புராணம் யாரைப் பற்றியது?", en: "Who is the Vishnu Purana about?" }, options: { ta: ["விஷ்ணு", "சிவன்", "பிரம்மா", "சூரியன்"], en: ["Vishnu", "Shiva", "Brahma", "Surya"] }, answer: 0 },
      { question: { ta: "புராணங்களில் பொதுவாக என்ன உள்ளது?", en: "What is generally found in the Puranas?" }, options: { ta: ["கதைகள், பாரம்பரியம், இதிகாசம்", "சட்டங்கள் மட்டும்", "வரலாறு மட்டும்", "காவியம் மட்டும்"], en: ["Stories, traditions, history", "Laws only", "History only", "Epics only"] }, answer: 0 },
      { question: { ta: "புராணங்கள் எந்த மொழியில் உள்ளன?", en: "In which language are the Puranas?" }, options: { ta: ["சமஸ்கிருதம்", "தமிழ்", "இந்தி", "அனைத்தும்"], en: ["Sanskrit", "Tamil", "Hindi", "All of these"] }, answer: 3 },
      { question: { ta: "புராணங்களின் ஆசிரியர் யார்?", en: "Who is the author of the Puranas?" }, options: { ta: ["வியாசர்", "வால்மீகி", "காளிதாசர்", "துளசிதாஸ்"], en: ["Vyasa", "Valmiki", "Kalidasa", "Tulsidas"] }, answer: 0 },
      { question: { ta: "புராணங்களின் மற்றொரு பெயர் என்ன?", en: "What is another name for the Puranas?" }, options: { ta: ["ஐந்தாம் வேதம்", "ஆறாம் வேதம்", "இதிகாசம்", "தர்சனம்"], en: ["Fifth Veda", "Sixth Veda", "Itihasa", "Darshana"] }, answer: 0 },
      { question: { ta: "ஸ்கந்த புராணம் யாரைப் பற்றியது?", en: "Who is the Skanda Purana about?" }, options: { ta: ["முருகன்", "சிவன்", "விஷ்ணு", "பிரம்மா"], en: ["Murugan", "Shiva", "Vishnu", "Brahma"] }, answer: 0 },
      { question: { ta: "கருட புராணம் யாரைப் பற்றியது?", en: "Who is the Garuda Purana about?" }, options: { ta: ["விஷ்ணு", "சிவன்", "பிரம்மா", "இந்திரன்"], en: ["Vishnu", "Shiva", "Brahma", "Indra"] }, answer: 0 },
      { question: { ta: "நாரத புராணம் யாரைப் பற்றியது?", en: "Who is the Narada Purana about?" }, options: { ta: ["நாரதர்", "விஷ்ணு", "சிவன்", "பிரம்மா"], en: ["Narada", "Vishnu", "Shiva", "Brahma"] }, answer: 0 },
      { question: { ta: "புராணங்களின் முக்கிய பிரிவுகள் யாவை?", en: "What are the main divisions of the Puranas?" }, options: { ta: ["தன்மை, பாரம்பரியம், கதை", "சட்டம் மட்டும்", "வரலாறு மட்டும்", "இதிகாசம் மட்டும்"], en: ["Dharma, tradition, stories", "Law only", "History only", "Epics only"] }, answer: 0 },
      { question: { ta: "புராணங்களின் படி பூமி எவ்வளவு காலம் நிலைத்திருக்கும்?", en: "According to the Puranas, how long does the earth last?" }, options: { ta: ["மன்வந்திரங்கள்", "வருடங்கள்", "நூற்றாண்டுகள்", "மாதங்கள்"], en: ["Manvantaras", "Years", "Centuries", "Months"] }, answer: 0 },
      { question: { ta: "புராணங்களில் 'கல்பம்' என்றால் என்ன?", en: "What does 'Kalpa' mean in the Puranas?" }, options: { ta: ["ஒரு சிருஷ்டி சுழற்சி", "ஒரு நாள்", "ஒரு வருடம்", "ஒரு மாதம்"], en: ["A cycle of creation", "A day", "A year", "A month"] }, answer: 0 },
    ],
  },
  // ── CATEGORY 15 ──
  {
    id: "saints",
    title: { ta: "இந்து ஞானிகள் மற்றும் அடியார்கள்", en: "Hindu Saints & Sages" },
    description: { ta: "அடியார்கள், ஞானிகள் மற்றும் அவர்களின் வரலாறு", en: "Saints, sages and their history" },
    icon: "people",
    color: "#4A148C",
    questions: [
      { question: { ta: "ஆதி சங்கரர் எந்த நூற்றாண்டில் வாழ்ந்தார்?", en: "In which century did Adi Shankara live?" }, options: { ta: ["8ம் நூற்றாண்டு", "5ம் நூற்றாண்டு", "10ம் நூற்றாண்டு", "12ம் நூற்றாண்டு"], en: ["8th century", "5th century", "10th century", "12th century"] }, answer: 0 },
      { question: { ta: "ராமானுஜர் எந்த நூற்றாண்டில் வாழ்ந்தார்?", en: "In which century did Ramanuja live?" }, options: { ta: ["11-12ம் நூற்றாண்டு", "8ம் நூற்றாண்டு", "15ம் நூற்றாண்டு", "18ம் நூற்றாண்டு"], en: ["11-12th century", "8th century", "15th century", "18th century"] }, answer: 0 },
      { question: { ta: "மத்வர் எந்த நூற்றாண்டில் வாழ்ந்தார்?", en: "In which century did Madhva live?" }, options: { ta: ["13ம் நூற்றாண்டு", "8ம் நூற்றாண்டு", "11ம் நூற்றாண்டு", "15ம் நூற்றாண்டு"], en: ["13th century", "8th century", "11th century", "15th century"] }, answer: 0 },
      { question: { ta: "சைவ சமயத்தின் முக்கிய அடியார்கள் யார்?", en: "Who are the main saints of Saivism?" }, options: { ta: ["நாயன்மார்கள்", "ஆழ்வார்கள்", "சித்தர்கள்", "முனிவர்கள்"], en: ["Nayanmars", "Azhwars", "Siddhars", "Munivars"] }, answer: 0 },
      { question: { ta: "வைணவ சமயத்தின் முக்கிய அடியார்கள் யார்?", en: "Who are the main saints of Vaishnavism?" }, options: { ta: ["ஆழ்வார்கள்", "நாயன்மார்கள்", "சித்தர்கள்", "முனிவர்கள்"], en: ["Azhwars", "Nayanmars", "Siddhars", "Munivars"] }, answer: 0 },
      { question: { ta: "வசிஷ்ட முனிவர் யாருடைய குரு?", en: "Whose guru is Sage Vashishta?" }, options: { ta: ["இக்ஷ்வாகு குலத்தார்", "சூர்ய வம்சத்தார்", "சந்திர வம்சத்தார்", "அனைவருக்கும்"], en: ["Ikshvaku dynasty", "Surya dynasty", "Chandra dynasty", "All"] }, answer: 0 },
      { question: { ta: "விஷ்வாமித்திர முனிவர் எந்த சமயத்தை சேர்ந்தவர்?", en: "Which period did Sage Vishwamitra belong to?" }, options: { ta: ["திரேதா யுகம்", "சத்ய யுகம்", "துவாபர யுகம்", "கலி யுகம்"], en: ["Treta Yuga", "Satya Yuga", "Dwapara Yuga", "Kali Yuga"] }, answer: 0 },
      { question: { ta: "கௌதம புத்தர் இந்து மதத்தில் எவ்வாறு கருதப்படுகிறார்?", en: "How is Gautama Buddha regarded in Hinduism?" }, options: { ta: ["விஷ்ணுவின் அவதாரம்", "சிவனின் அவதாரம்", "பிரம்மாவின் அவதாரம்", "ஒரு முனிவர்"], en: ["An avatar of Vishnu", "An avatar of Shiva", "An avatar of Brahma", "A sage"] }, answer: 0 },
      { question: { ta: "சீதையின் தந்தை யார்?", en: "Who is Sita's father?" }, options: { ta: ["ஜனகர்", "தசரதர்", "வசிஷ்டர்", "விஷ்வாமித்திரர்"], en: ["Janaka", "Dasharatha", "Vashishta", "Vishwamitra"] }, answer: 0 },
      { question: { ta: "துருவனின் கதை எந்த புராணத்தில் உள்ளது?", en: "In which Purana is Dhruva's story found?" }, options: { ta: ["விஷ்ணு புராணம்", "சிவ புராணம்", "பாகவத புராணம்", "கருட புராணம்"], en: ["Vishnu Purana", "Shiva Purana", "Bhagavata Purana", "Garuda Purana"] }, answer: 0 },
      { question: { ta: "பிரஹலாதனின் கதை எந்த புராணத்தில் உள்ளது?", en: "In which Purana is Prahlada's story found?" }, options: { ta: ["விஷ்ணு புராணம்", "சிவ புராணம்", "பாகவத புராணம்", "கருட புராணம்"], en: ["Vishnu Purana", "Shiva Purana", "Bhagavata Purana", "Garuda Purana"] }, answer: 0 },
      { question: { ta: "மார்க்கண்டேயரின் கதை எந்த புராணத்தில் உள்ளது?", en: "In which Purana is Markandeya's story found?" }, options: { ta: ["சிவ புராணம்", "விஷ்ணு புராணம்", "பாகவத புராணம்", "கருட புராணம்"], en: ["Shiva Purana", "Vishnu Purana", "Bhagavata Purana", "Garuda Purana"] }, answer: 0 },
      { question: { ta: "சாவித்திரியின் கதை எந்த புராணத்தில் உள்ளது?", en: "In which Purana is Savitri's story found?" }, options: { ta: ["மார்க்கண்டேய புராணம்", "விஷ்ணு புராணம்", "சிவ புராணம்", "பாகவத புராணம்"], en: ["Markandeya Purana", "Vishnu Purana", "Shiva Purana", "Bhagavata Purana"] }, answer: 0 },
      { question: { ta: "திருவள்ளுவர் எந்த சமயத்தை சேர்ந்தவர்?", en: "Which religion did Thiruvalluvar belong to?" }, options: { ta: ["இந்து", "பௌத்த", "சமண", "கிறிஸ்தவ"], en: ["Hindu", "Buddhist", "Jain", "Christian"] }, answer: 0 },
      { question: { ta: "திருவள்ளுவரின் படைப்பு எது?", en: "What is Thiruvalluvar's work?" }, options: { ta: ["திருக்குறள்", "சிலப்பதிகாரம்", "மணிமேகலை", "தேவாரம்"], en: ["Thirukkural", "Silappathikaram", "Manimekalai", "Thevaram"] }, answer: 0 },
    ],
  },
  // ── CATEGORY 16 ──
  {
    id: "ayurveda",
    title: { ta: "ஆயுர்வேதம்", en: "Ayurveda" },
    description: { ta: "பாரம்பரிய மருத்துவம், மூலிகைகள் மற்றும் சிகிச்சை", en: "Traditional medicine, herbs and treatments" },
    icon: "health-and-safety",
    color: "#2E7D32",
    questions: [
      { question: { ta: "ஆயுர்வேதத்தின் பிதா யார்?", en: "Who is the father of Ayurveda?" }, options: { ta: ["சுஷ்ருதர்", "சரகர்", "வாக்படர்", "பதஞ்சலி"], en: ["Sushruta", "Charaka", "Vagbhata", "Patanjali"] }, answer: 0 },
      { question: { ta: "ஆயுர்வேதத்தில் உள்ள மூன்று தோஷங்கள் யாவை?", en: "What are the three doshas in Ayurveda?" }, options: { ta: ["வாதம், பித்தம், கபம்", "சூரியன், சந்திரன், பூமி", "ஆத்மா, மனம், உடல்", "ஞானம், பக்தி, கர்மா"], en: ["Vata, Pitta, Kapha", "Sun, Moon, Earth", "Soul, Mind, Body", "Gnana, Bhakti, Karma"] }, answer: 0 },
      { question: { ta: "சுஷ்ருதர் எதற்கு பிரபலமானவர்?", en: "What is Sushruta famous for?" }, options: { ta: ["அறுவை சிகிச்சை", "மூலிகை மருத்துவம்", "கண் மருத்துவம்", "மனநோய் சிகிச்சை"], en: ["Surgery", "Herbal medicine", "Eye treatment", "Mental health"] }, answer: 0 },
      { question: { ta: "சரகரின் படைப்பு எது?", en: "What is Charaka's work?" }, options: { ta: ["சரக சம்ஹிதை", "சுஷ்ருத சம்ஹிதை", "அஷ்டாங்க ஹிருதயம்", "பகவத் கீதை"], en: ["Charaka Samhita", "Sushruta Samhita", "Ashtanga Hridaya", "Bhagavad Gita"] }, answer: 0 },
      { question: { ta: "ஆயுர்வேதத்தின் அடிப்படை நூல் எது?", en: "What is the basic text of Ayurveda?" }, options: { ta: ["சரக சம்ஹிதை", "வேதங்கள்", "உபநிடதங்கள்", "புராணங்கள்"], en: ["Charaka Samhita", "Vedas", "Upanishads", "Puranas"] }, answer: 0 },
      { question: { ta: "ஆயுர்வேதத்தில் 'ரஸாயனம்' என்றால் என்ன?", en: "What does 'Rasayana' mean in Ayurveda?" }, options: { ta: ["மீளாயுச்சத்தி மருத்துவம்", "அறுவை சிகிச்சை", "மூலிகை மருத்துவம்", "தியானம்"], en: ["Rejuvenation therapy", "Surgery", "Herbal medicine", "Meditation"] }, answer: 0 },
      { question: { ta: "ஆயுர்வேதம் எந்த வேதத்தின் ஒரு பகுதி?", en: "Which Veda is Ayurveda a part of?" }, options: { ta: ["அதர்வண வேதம்", "ரிக் வேதம்", "சாம வேதம்", "யஜுர் வேதம்"], en: ["Atharva Veda", "Rig Veda", "Sama Veda", "Yajur Veda"] }, answer: 0 },
      { question: { ta: "ஆயுர்வேதத்தில் 'பஞ்ச கர்மா' என்றால் என்ன?", en: "What is 'Pancha Karma' in Ayurveda?" }, options: { ta: ["ஐந்து சிகிச்சை முறைகள்", "ஐந்து மூலிகைகள்", "ஐந்து தோஷங்கள்", "ஐந்து நோய்கள்"], en: ["Five treatment methods", "Five herbs", "Five doshas", "Five diseases"] }, answer: 0 },
      { question: { ta: "ஆயுர்வேத மருத்துவம் எந்த நாட்டில் தொடங்கியது?", en: "In which country did Ayurvedic medicine originate?" }, options: { ta: ["இந்தியா", "சீனா", "ஈஜிப்து", "கிரீஸ்"], en: ["India", "China", "Egypt", "Greece"] }, answer: 0 },
      { question: { ta: "ஆயுர்வேதத்தின் மற்றொரு பெயர் என்ன?", en: "What is another name for Ayurveda?" }, options: { ta: ["வேத மருத்துவம்", "சித்த மருத்துவம்", "யுனானி மருத்துவம்", "ஹோமியோபதி"], en: ["Vedic medicine", "Siddha medicine", "Unani medicine", "Homeopathy"] }, answer: 0 },
      { question: { ta: "ஆயுர்வேதத்தில் 'மூலிகை' எதற்கு பயன்படுத்தப்படுகிறது?", en: "What is 'herb' used for in Ayurveda?" }, options: { ta: ["மருந்துக்கு", "உணவுக்கு", "அலங்காரத்திற்கு", "சடங்கிற்கு"], en: ["Medicine", "Food", "Decoration", "Ritual"] }, answer: 0 },
      { question: { ta: "ஆயுர்வேதம் எதை வலியுறுத்துகிறது?", en: "What does Ayurveda emphasize?" }, options: { ta: ["தடுப்பு மற்றும் சிகிச்சை", "அறுவை சிகிச்சை மட்டும்", "மூலிகை மட்டும்", "தியானம் மட்டும்"], en: ["Prevention and treatment", "Surgery only", "Herbs only", "Meditation only"] }, answer: 0 },
      { question: { ta: "ஆயுர்வேதத்தில் 'தினச்சர்யா' என்றால் என்ன?", en: "What is 'Dinacharya' in Ayurveda?" }, options: { ta: ["தினசரி பழக்கவழக்கங்கள்", "வாராந்திர பழக்கங்கள்", "மாதாந்திர பழக்கங்கள்", "வருடாந்திர பழக்கங்கள்"], en: ["Daily routine", "Weekly routine", "Monthly routine", "Yearly routine"] }, answer: 0 },
      { question: { ta: "ஆயுர்வேதத்தில் 'சத்வா' என்றால் என்ன?", en: "What is 'Sattva' in Ayurveda?" }, options: { ta: ["தூய்மை", "இருமை", "துக்கம்", "அறியாமை"], en: ["Purity", "Duality", "Sorrow", "Ignorance"] }, answer: 0 },
      { question: { ta: "ஆயுர்வேதத்தின் மொத்த நூல்கள் எத்தனை?", en: "How many total texts are there in Ayurveda?" }, options: { ta: ["3 முக்கிய நூல்கள்", "1 நூல்", "5 நூல்கள்", "10 நூல்கள்"], en: ["3 main texts", "1 text", "5 texts", "10 texts"] }, answer: 0 },
    ],
  },
  // ── CATEGORY 17 ──
  {
    id: "yoga_sutras",
    title: { ta: "யோக சூத்திரங்கள்", en: "Yoga Sutras" },
    description: { ta: "பதஞ்சலியின் யோக சூத்திரங்களின் போதனைகள்", en: "Teachings of Patanjali's Yoga Sutras" },
    icon: "self-improvement",
    color: "#F57F17",
    questions: [
      { question: { ta: "யோக சூத்திரங்களின் ஆசிரியர் யார்?", en: "Who is the author of the Yoga Sutras?" }, options: { ta: ["பதஞ்சலி", "கௌதமர்", "கனாடர்", "ஜைமினி"], en: ["Patanjali", "Gautama", "Kanada", "Jaimini"] }, answer: 0 },
      { question: { ta: "யோக சூத்திரங்களில் எத்தனை பாதங்கள் உள்ளன?", en: "How many padas are there in the Yoga Sutras?" }, options: { ta: ["4", "3", "5", "6"], en: ["4", "3", "5", "6"] }, answer: 0 },
      { question: { ta: "யோக சூத்திரங்களின் முதல் பாதம் எது?", en: "What is the first pada of the Yoga Sutras?" }, options: { ta: ["சமாதி பாதம்", "சாதன பாதம்", "விபூதி பாதம்", "கைவல்ய பாதம்"], en: ["Samadhi Pada", "Sadhana Pada", "Vibhuti Pada", "Kaivalya Pada"] }, answer: 0 },
      { question: { ta: "யோக சூத்திரங்களின் இரண்டாவது பாதம் எது?", en: "What is the second pada of the Yoga Sutras?" }, options: { ta: ["சாதன பாதம்", "சமாதி பாதம்", "விபூதி பாதம்", "கைவல்ய பாதம்"], en: ["Sadhana Pada", "Samadhi Pada", "Vibhuti Pada", "Kaivalya Pada"] }, answer: 0 },
      { question: { ta: "யோக சூத்திரங்களின் மூன்றாவது பாதம் எது?", en: "What is the third pada of the Yoga Sutras?" }, options: { ta: ["விபூதி பாதம்", "சாதன பாதம்", "சமாதி பாதம்", "கைவல்ய பாதம்"], en: ["Vibhuti Pada", "Sadhana Pada", "Samadhi Pada", "Kaivalya Pada"] }, answer: 0 },
      { question: { ta: "யோக சூத்திரங்களின் நான்காவது பாதம் எது?", en: "What is the fourth pada of the Yoga Sutras?" }, options: { ta: ["கைவல்ய பாதம்", "விபூதி பாதம்", "சாதன பாதம்", "சமாதி பாதம்"], en: ["Kaivalya Pada", "Vibhuti Pada", "Sadhana Pada", "Samadhi Pada"] }, answer: 0 },
      { question: { ta: "யோக சூத்திரங்களில் உள்ள மொத்த சூத்திரங்கள் எத்தனை?", en: "How many sutras are there in the Yoga Sutras?" }, options: { ta: ["195", "150", "200", "250"], en: ["195", "150", "200", "250"] }, answer: 0 },
      { question: { ta: "யோக சூத்திரங்களில் 'சித் விருத்தி நிரோத:' என்றால் என்ன?", en: "What does 'Chitta Vritti Nirodhah' mean in the Yoga Sutras?" }, options: { ta: ["மனதின் மாற்றங்களை நிறுத்துதல்", "மனதை விரிவுபடுத்துதல்", "மனதை கட்டுப்படுத்துதல்", "மனதை விடுவித்தல்"], en: ["Stopping the modifications of the mind", "Expanding the mind", "Controlling the mind", "Freeing the mind"] }, answer: 0 },
      { question: { ta: "யோக சூத்திரங்களின் முதல் சூத்திரம் என்ன?", en: "What is the first sutra of the Yoga Sutras?" }, options: { ta: ["அத யோகானுசாசனம்", "யோக சித்த விருத்தி நிரோத:", "ததஸ்து அர்த்தம்", "சமாதி"], en: ["Atha Yoganushasanam", "Yoga Chitta Vritti Nirodhah", "Tadastu Artham", "Samadhi"] }, answer: 0 },
      { question: { ta: "யோக சூத்திரங்களில் 'அப்யாசம்' என்றால் என்ன?", en: "What is 'Abhyasa' in the Yoga Sutras?" }, options: { ta: ["தொடர்ச்சியான பயிற்சி", "ஒருமுறை பயிற்சி", "தியானம்", "மூச்சுப் பயிற்சி"], en: ["Continuous practice", "One-time practice", "Meditation", "Breath practice"] }, answer: 0 },
      { question: { ta: "யோக சூத்திரங்களில் 'வைராக்யம்' என்றால் என்ன?", en: "What is 'Vairagya' in the Yoga Sutras?" }, options: { ta: ["பற்றின்மை", "பயம்", "கோபம்", "பேராசை"], en: ["Detachment", "Fear", "Anger", "Greed"] }, answer: 0 },
      { question: { ta: "யோக சூத்திரங்களில் 'ஈஸ்வர பிரணிதானம்' என்றால் என்ன?", en: "What is 'Ishvara Pranidhana' in the Yoga Sutras?" }, options: { ta: ["இறைவனிடம் அர்ப்பணிப்பு", "தியானம்", "மூச்சுப் பயிற்சி", "தானம்"], en: ["Surrender to God", "Meditation", "Breath practice", "Charity"] }, answer: 0 },
      { question: { ta: "யோக சூத்திரங்களில் 'அஹிம்சை' எந்த அங்கத்தில் உள்ளது?", en: "In which limb is 'Ahimsa' in the Yoga Sutras?" }, options: { ta: ["யமம்", "நியமம்", "ஆசனம்", "பிராணாயாமம்"], en: ["Yama", "Niyama", "Asana", "Pranayama"] }, answer: 0 },
      { question: { ta: "யோக சூத்திரங்களில் 'ஸமாதி' என்றால் என்ன?", en: "What is 'Samadhi' in the Yoga Sutras?" }, options: { ta: ["உச்ச நிலை ஞானம்", "தியானம்", "மூச்சுப் பயிற்சி", "உடல் பயிற்சி"], en: ["Supreme state of consciousness", "Meditation", "Breath practice", "Physical practice"] }, answer: 0 },
      { question: { ta: "யோக சூத்திரங்களின் கடைசி பாதம் எது?", en: "What is the last pada of the Yoga Sutras?" }, options: { ta: ["கைவல்ய பாதம்", "விபூதி பாதம்", "சாதன பாதம்", "சமாதி பாதம்"], en: ["Kaivalya Pada", "Vibhuti Pada", "Sadhana Pada", "Samadhi Pada"] }, answer: 0 },
    ],
  },
  // ── CATEGORY 18 ──
  {
    id: "tamil_literature",
    title: { ta: "தமிழ் இலக்கியம்", en: "Tamil Literature" },
    description: { ta: "பண்டைய தமிழ் இலக்கியங்கள் மற்றும் அவற்றின் சிறப்புகள்", en: "Ancient Tamil literature and their specialties" },
    icon: "library-books",
    color: "#C62828",
    questions: [
      { question: { ta: "தமிழின் பழமையான இலக்கியம் எது?", en: "What is the oldest Tamil literature?" }, options: { ta: ["தொல்காப்பியம்", "திருக்குறள்", "சிலப்பதிகாரம்", "மணிமேகலை"], en: ["Tholkappiyam", "Thirukkural", "Silappathikaram", "Manimekalai"] }, answer: 0 },
      { question: { ta: "தொல்காப்பியத்தின் ஆசிரியர் யார்?", en: "Who is the author of Tholkappiyam?" }, options: { ta: ["தொல்காப்பியர்", "திருவள்ளுவர்", "இளங்கோவடிகள்", "சாத்தனார்"], en: ["Tholkappiyar", "Thiruvalluvar", "Ilangovadigal", "Sathanar"] }, answer: 0 },
      { question: { ta: "திருக்குறளில் எத்தனை அதிகாரங்கள் உள்ளன?", en: "How many chapters are there in Thirukkural?" }, options: { ta: ["133", "100", "150", "200"], en: ["133", "100", "150", "200"] }, answer: 0 },
      { question: { ta: "திருக்குறளில் எத்தனை பால்கள் உள்ளன?", en: "How many parts are there in Thirukkural?" }, options: { ta: ["3", "2", "4", "5"], en: ["3", "2", "4", "5"] }, answer: 0 },
      { question: { ta: "சிலப்பதிகாரத்தின் ஆசிரியர் யார்?", en: "Who is the author of Silappathikaram?" }, options: { ta: ["இளங்கோவடிகள்", "திருவள்ளுவர்", "சாத்தனார்", "தொல்காப்பியர்"], en: ["Ilangovadigal", "Thiruvalluvar", "Sathanar", "Tholkappiyar"] }, answer: 0 },
      { question: { ta: "மணிமேகலையின் ஆசிரியர் யார்?", en: "Who is the author of Manimekalai?" }, options: { ta: ["சாத்தனார்", "இளங்கோவடிகள்", "திருவள்ளுவர்", "தொல்காப்பியர்"], en: ["Sathanar", "Ilangovadigal", "Thiruvalluvar", "Tholkappiyar"] }, answer: 0 },
      { question: { ta: "தமிழ் இலக்கியத்தின் முதல் வகைப்பாடு எது?", en: "What is the first classification in Tamil literature?" }, options: { ta: ["அகம் மற்றும் புறம்", "இன்பம் மற்றும் துன்பம்", "ஞானம் மற்றும் அஞ்ஞானம்", "இந்து மற்றும் பௌத்தம்"], en: ["Akam and Puram", "Happiness and Sorrow", "Knowledge and Ignorance", "Hindu and Buddhist"] }, answer: 0 },
      { question: { ta: "தமிழ் இலக்கியத்தில் 'அகம்' என்றால் என்ன?", en: "What is 'Akam' in Tamil literature?" }, options: { ta: ["உள் வாழ்க்கை", "வெளி வாழ்க்கை", "அரசியல்", "போர்"], en: ["Inner life", "Outer life", "Politics", "War"] }, answer: 0 },
      { question: { ta: "தமிழ் இலக்கியத்தில் 'புறம்' என்றால் என்ன?", en: "What is 'Puram' in Tamil literature?" }, options: { ta: ["வெளி வாழ்க்கை", "உள் வாழ்க்கை", "காதல்", "தியானம்"], en: ["Outer life", "Inner life", "Love", "Meditation"] }, answer: 0 },
      { question: { ta: "தமிழ் இலக்கியத்தின் சங்க காலம் எத்தனை?", en: "How many Sangam periods are there in Tamil literature?" }, options: { ta: ["3", "2", "4", "5"], en: ["3", "2", "4", "5"] }, answer: 0 },
      { question: { ta: "திருக்குறளை வேறு எந்த பெயரில் அழைக்கலாம்?", en: "What is another name for Thirukkural?" }, options: { ta: ["முப்பால்", "இரட்டைப்பால்", "நான்குபால்", "ஐந்துபால்"], en: ["Muppal", "Irattaippal", "Nankuppal", "Ainthuppal"] }, answer: 0 },
      { question: { ta: "திருவள்ளுவரின் தொழில் என்ன?", en: "What was Thiruvalluvar's occupation?" }, options: { ta: ["நெசவாளர்", "கவிஞர்", "வீரர்", "மன்னர்"], en: ["Weaver", "Poet", "Warrior", "King"] }, answer: 0 },
      { question: { ta: "திருவள்ளுவர் வாழ்ந்த காலம்?", en: "When did Thiruvalluvar live?" }, options: { ta: ["கி.மு. 3-4 நூற்றாண்டு", "கி.பி. 5-6 நூற்றாண்டு", "கி.மு. 1-2 நூற்றாண்டு", "கி.பி. 1-2 நூற்றாண்டு"], en: ["3-4 BCE", "5-6 CE", "1-2 BCE", "1-2 CE"] }, answer: 0 },
      { question: { ta: "தமிழ் இலக்கியத்தின் ஐந்து காப்பியங்கள் யாவை?", en: "What are the five epics of Tamil literature?" }, options: { ta: ["சிலப்பதிகாரம், மணிமேகலை, சீவக சிந்தாமணி, வளையாபதி, குண்டலகேசி", "இராமாயணம், மகாபாரதம், பகவத்கீதை, வேதங்கள், உபநிடதங்கள்", "திருக்குறள், தொல்காப்பியம், கலித்தொகை, நற்றிணை, அகநானூறு", "தேவாரம், திருவாசகம், திருப்புகழ், பெரியபுராணம்"], en: ["Silappathikaram, Manimekalai, Seevaka Chinthamani, Valaiyapathi, Kundalakesi", "Ramayana, Mahabharata, Bhagavad Gita, Vedas, Upanishads", "Thirukkural, Tholkappiyam, Kalithogai, Narrinai, Agananuru", "Thevaram, Thiruvasagam, Thiruppugazh, Periyapuranam"] }, answer: 0 },
      { question: { ta: "தமிழ் இலக்கியத்தின் 'குறுந்தொகை' எதைப் பற்றியது?", en: "What is 'Kurunthogai' about in Tamil literature?" }, options: { ta: ["குறுகிய காதல் பாடல்கள்", "நீண்ட காதல் பாடல்கள்", "போர் பாடல்கள்", "அரசியல் பாடல்கள்"], en: ["Short love poems", "Long love poems", "War poems", "Political poems"] }, answer: 0 },
    ],
  },
  // ── CATEGORY 19 ──
  {
    id: "hindu_culture",
    title: { ta: "இந்து கலாச்சாரம்", en: "Hindu Culture" },
    description: { ta: "இந்து கலாச்சாரம், பாரம்பரியங்கள் மற்றும் பழக்கவழக்கங்கள்", en: "Hindu culture, traditions and customs" },
    icon: "diversity-3",
    color: "#D84315",
    questions: [
      { question: { ta: "இந்து கலாச்சாரத்தில் 'கோலம்' என்றால் என்ன?", en: "What is 'Kolam' in Hindu culture?" }, options: { ta: ["தரையில் வரையப்படும் வடிவமைப்பு", "ஒரு ஆடை", "ஒரு உணவு", "ஒரு நடனம்"], en: ["Design drawn on the ground", "A garment", "A food", "A dance"] }, answer: 0 },
      { question: { ta: "திருமணத்தில் 'மாங்கல்யம்' எதைக் குறிக்கிறது?", en: "What does 'Mangalyam' represent in marriage?" }, options: { ta: ["தாலி", "மோதிரம்", "மாலை", "கையில் பூச்சு"], en: ["Thali", "Ring", "Garland", "Hand decoration"] }, answer: 0 },
      { question: { ta: "இந்து வீட்டில் நுழையும் போது எதை முதலில் காணலாம்?", en: "What can be seen first when entering a Hindu home?" }, options: { ta: ["கோலம்", "தூபம்", "தீபம்", "மணி"], en: ["Kolam", "Incense", "Lamp", "Bell"] }, answer: 0 },
      { question: { ta: "இந்து கலாச்சாரத்தில் 'அரிசி' எதற்கு பயன்படுத்தப்படுகிறது?", en: "What is 'rice' used for in Hindu culture?" }, options: { ta: ["புனித சடங்குகள்", "உணவு மட்டும்", "அலங்காரம்", "மருந்து"], en: ["Sacred rituals", "Food only", "Decoration", "Medicine"] }, answer: 0 },
      { question: { ta: "இந்து கலாச்சாரத்தில் 'மஞ்சள்' எதற்கு பயன்படுத்தப்படுகிறது?", en: "What is 'turmeric' used for in Hindu culture?" }, options: { ta: ["திருமணம், பூஜை, மருத்துவம்", "உணவு மட்டும்", "அலங்காரம்", "நடனம்"], en: ["Marriage, worship, medicine", "Food only", "Decoration", "Dance"] }, answer: 0 },
      { question: { ta: "இந்து கலாச்சாரத்தில் 'பழங்களை படைத்தல்' என்றால் என்ன?", en: "What is 'offering fruits' in Hindu culture?" }, options: { ta: ["கடவுளுக்கு காணிக்கை", "உணவு", "அலங்காரம்", "மருந்து"], en: ["Offering to God", "Food", "Decoration", "Medicine"] }, answer: 0 },
      { question: { ta: "இந்து கலாச்சாரத்தில் 'விரதம்' என்றால் என்ன?", en: "What is 'Vratam' in Hindu culture?" }, options: { ta: ["நோன்பு மற்றும் வழிபாடு", "திருவிழா", "நடனம்", "இசை"], en: ["Fasting and worship", "Festival", "Dance", "Music"] }, answer: 0 },
      { question: { ta: "இந்து கலாச்சாரத்தில் 'குழந்தை பிறப்பு' விழா என்ன?", en: "What is the 'child birth' ceremony in Hindu culture?" }, options: { ta: ["ஜாதக கர்மா", "உபநயனம்", "திருமணம்", "இறுதி சடங்கு"], en: ["Jatakarma", "Upanayana", "Marriage", "Funeral"] }, answer: 0 },
      { question: { ta: "இந்து கலாச்சாரத்தில் 'இறுதி சடங்கு' எப்படி செய்யப்படுகிறது?", en: "How is the 'funeral' performed in Hindu culture?" }, options: { ta: ["தகனம்", "புதைத்தல்", "நதியில் விடுதல்", "அனைத்தும்"], en: ["Cremation", "Burial", "Immersing in river", "All of these"] }, answer: 0 },
      { question: { ta: "இந்து கலாச்சாரத்தில் 'பித்ரு காரியம்' என்றால் என்ன?", en: "What is 'Pitru Karyam' in Hindu culture?" }, options: { ta: ["முன்னோர்களுக்கான சடங்குகள்", "குழந்தை பிறப்பு", "திருமணம்", "திருவிழா"], en: ["Rituals for ancestors", "Child birth", "Marriage", "Festival"] }, answer: 0 },
      { question: { ta: "இந்து கலாச்சாரத்தில் 'சாந்தி' என்றால் என்ன?", en: "What is 'Shanti' in Hindu culture?" }, options: { ta: ["அமைதி", "போர்", "சண்டை", "கோபம்"], en: ["Peace", "War", "Fight", "Anger"] }, answer: 0 },
      { question: { ta: "இந்து கலாச்சாரத்தில் 'தர்மம்' என்றால் என்ன?", en: "What is 'Dharma' in Hindu culture?" }, options: { ta: ["நீதி மற்றும் கடமை", "அநீதி", "கடமையற்ற தன்மை", "சுயநலம்"], en: ["Righteousness and duty", "Injustice", "Irresponsibility", "Selfishness"] }, answer: 0 },
      { question: { ta: "இந்து கலாச்சாரத்தில் 'திருநீறு' என்றால் என்ன?", en: "What is 'Thiruneeru' in Hindu culture?" }, options: { ta: ["புனித விபூதி", "சந்தனம்", "குங்குமம்", "துளசி"], en: ["Sacred ash", "Sandalwood", "Kumkum", "Tulsi"] }, answer: 0 },
      { question: { ta: "இந்து கலாச்சாரத்தில் 'குடும்ப மரம்' எதைக் குறிக்கிறது?", en: "What does 'family tree' represent in Hindu culture?" }, options: { ta: ["வம்சாவளி", "சொத்து", "பெயர்", "இடம்"], en: ["Ancestry", "Property", "Name", "Place"] }, answer: 0 },
      { question: { ta: "இந்து கலாச்சாரத்தின் அடிப்படை மதிப்பு என்ன?", en: "What is the fundamental value of Hindu culture?" }, options: { ta: ["அகிம்சை", "வன்முறை", "தீமை", "போர்"], en: ["Non-violence", "Violence", "Evil", "War"] }, answer: 0 },
    ],
  },
  // ── CATEGORY 20 ──
  {
    id: "hindu_astrology",
    title: { ta: "இந்து ஜோதிடம்", en: "Hindu Astrology" },
    description: { ta: "ஜோதிடம், கிரகங்கள், ராசிகள் மற்றும் நட்சத்திரங்கள்", en: "Astrology, planets, zodiac signs and stars" },
    icon: "stars",
    color: "#6A1B9A",
    questions: [
      { question: { ta: "இந்து ஜோதிடத்தில் உள்ள 9 கிரகங்கள் யாவை?", en: "What are the 9 planets in Hindu astrology?" }, options: { ta: ["சூரியன், சந்திரன், செவ்வாய், புதன், குரு, சுக்கிரன், சனி, ராகு, கேது", "சூரியன், சந்திரன், செவ்வாய், புதன், குரு, சுக்கிரன், சனி, யுரேனஸ், நெப்டியூன்", "சூரியன், சந்திரன், பூமி, செவ்வாய், புதன், குரு, சுக்கிரன், சனி, புளூட்டோ", "வெள்ளி, செவ்வாய், புதன், குரு, சுக்கிரன், சனி, யுரேனஸ், நெப்டியூன், புளூட்டோ"], en: ["Sun, Moon, Mars, Mercury, Jupiter, Venus, Saturn, Rahu, Ketu", "Sun, Moon, Mars, Mercury, Jupiter, Venus, Saturn, Uranus, Neptune", "Sun, Moon, Earth, Mars, Mercury, Jupiter, Venus, Saturn, Pluto", "Venus, Mars, Mercury, Jupiter, Venus, Saturn, Uranus, Neptune, Pluto"] }, answer: 0 },
      { question: { ta: "இந்து ஜோதிடத்தில் உள்ள 12 ராசிகள் யாவை?", en: "What are the 12 zodiac signs in Hindu astrology?" }, options: { ta: ["மேஷம், ரிஷபம், மிதுனம், கடகம், சிம்மம், கன்னி, துலாம், விருச்சிகம், தனுசு, மகரம், கும்பம், மீனம்", "ஏப்ரல், மே, ஜூன், ஜூலை, ஆகஸ்ட், செப்டம்பர், அக்டோபர், நவம்பர், டிசம்பர், ஜனவரி, பிப்ரவரி, மார்ச்", "கிழக்கு, மேற்கு, வடக்கு, தெற்கு, வடகிழக்கு, தென்கிழக்கு, வடமேற்கு, தென்மேற்கு, கிழக்கு, மேற்கு, வடக்கு, தெற்கு", "ஞாயிறு, திங்கள், செவ்வாய், புதன், வியாழன், வெள்ளி, சனி, ஞாயிறு, திங்கள், செவ்வாய், புதன், வியாழன்"], en: ["Aries, Taurus, Gemini, Cancer, Leo, Virgo, Libra, Scorpio, Sagittarius, Capricorn, Aquarius, Pisces", "April, May, June, July, August, September, October, November, December, January, February, March", "East, West, North, South, Northeast, Southeast, Northwest, Southwest, East, West, North, South", "Sunday, Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, Sunday, Monday, Tuesday, Wednesday, Thursday"] }, answer: 0 },
      { question: { ta: "ஜோதிடத்தில் 'நட்சத்திரம்' என்றால் என்ன?", en: "What is 'Nakshatra' in astrology?" }, options: { ta: ["27 நட்சத்திரங்கள்", "12 நட்சத்திரங்கள்", "9 நட்சத்திரங்கள்", "30 நட்சத்திரங்கள்"], en: ["27 stars", "12 stars", "9 stars", "30 stars"] }, answer: 0 },
      { question: { ta: "ஜோதிடத்தில் 'ஜாதகம்' என்றால் என்ன?", en: "What is 'Jathagam' in astrology?" }, options: { ta: ["பிறந்த சாதகம்", "திருமண சாதகம்", "இறப்பு சாதகம்", "வேலை சாதகம்"], en: ["Birth chart", "Marriage chart", "Death chart", "Job chart"] }, answer: 0 },
      { question: { ta: "ஜோதிடத்தில் 'ராசி' என்றால் என்ன?", en: "What is 'Rasi' in astrology?" }, options: { ta: ["12 ராசிகள்", "27 ராசிகள்", "9 ராசிகள்", "30 ராசிகள்"], en: ["12 zodiac signs", "27 zodiac signs", "9 zodiac signs", "30 zodiac signs"] }, answer: 0 },
      { question: { ta: "ஜோதிடத்தில் 'பாவம்' என்றால் என்ன?", en: "What is 'Bhavam' in astrology?" }, options: { ta: ["12 பாவங்கள்", "27 பாவங்கள்", "9 பாவங்கள்", "30 பாவங்கள்"], en: ["12 houses", "27 houses", "9 houses", "30 houses"] }, answer: 0 },
      { question: { ta: "இந்து ஜோதிடம் எந்த மொழியில் உள்ளது?", en: "In which language is Hindu astrology?" }, options: { ta: ["சமஸ்கிருதம்", "தமிழ்", "இந்தி", "அனைத்தும்"], en: ["Sanskrit", "Tamil", "Hindi", "All of these"] }, answer: 3 },
      { question: { ta: "ஜோதிடத்தில் 'கேது' என்றால் என்ன?", en: "What is 'Ketu' in astrology?" }, options: { ta: ["ஒரு நிழல் கிரகம்", "ஒரு உண்மையான கிரகம்", "ஒரு நட்சத்திரம்", "ஒரு ராசி"], en: ["A shadow planet", "A real planet", "A star", "A zodiac sign"] }, answer: 0 },
      { question: { ta: "ஜோதிடத்தில் 'ராகு' என்றால் என்ன?", en: "What is 'Rahu' in astrology?" }, options: { ta: ["ஒரு நிழல் கிரகம்", "ஒரு உண்மையான கிரகம்", "ஒரு நட்சத்திரம்", "ஒரு ராசி"], en: ["A shadow planet", "A real planet", "A star", "A zodiac sign"] }, answer: 0 },
      { question: { ta: "ஜோதிடத்தில் 'தசை' என்றால் என்ன?", en: "What is 'Dasha' in astrology?" }, options: { ta: ["கிரக காலம்", "நட்சத்திரம்", "ராசி", "பாவம்"], en: ["Planetary period", "Star", "Zodiac sign", "House"] }, answer: 0 },
      { question: { ta: "ஜோதிடத்தில் 'கோணம்' என்றால் என்ன?", en: "What is 'Konam' in astrology?" }, options: { ta: ["கிரக இடப்பெயர்வு", "நட்சத்திர இடம்", "ராசி இடம்", "பாவ இடம்"], en: ["Planetary position", "Star position", "Zodiac position", "House position"] }, answer: 0 },
      { question: { ta: "ஜோதிடத்தில் 'அம்சம்' என்றால் என்ன?", en: "What is 'Amsam' in astrology?" }, options: { ta: ["கிரக பகுதி", "நட்சத்திர பகுதி", "ராசி பகுதி", "பாவ பகுதி"], en: ["Planetary division", "Star division", "Zodiac division", "House division"] }, answer: 0 },
      { question: { ta: "இந்து ஜோதிடத்தின் பிதா யார்?", en: "Who is the father of Hindu astrology?" }, options: { ta: ["பராசரர்", "வராகமிகிரர்", "கௌதமர்", "கனாடர்"], en: ["Parashara", "Varahamihira", "Gautama", "Kanada"] }, answer: 0 },
      { question: { ta: "ஜோதிடத்தில் 'பிருஹத்ஸம்ஹிதை' யாருடைய படைப்பு?", en: "Whose creation is 'Brihat Samhita' in astrology?" }, options: { ta: ["வராகமிகிரர்", "பராசரர்", "கௌதமர்", "கனாடர்"], en: ["Varahamihira", "Parashara", "Gautama", "Kanada"] }, answer: 0 },
      { question: { ta: "ஜோதிடத்தில் 'இடம்' என்றால் என்ன?", en: "What is 'Place' in astrology?" }, options: { ta: ["கிரகத்தின் இடம்", "நட்சத்திரத்தின் இடம்", "ராசியின் இடம்", "பாவத்தின் இடம்"], en: ["Planet's position", "Star's position", "Zodiac's position", "House's position"] }, answer: 0 },
    ],
  },
];

export const getQuizCategory = (categoryId) =>
  QUIZ_CATEGORIES.find((category) => category.id === categoryId);